// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/oms/oms.proto

package oms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type HelloResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{2}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{3}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

type ErrResponse struct {
	//错误类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	//错误具体信息
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrResponse) Reset()         { *m = ErrResponse{} }
func (m *ErrResponse) String() string { return proto.CompactTextString(m) }
func (*ErrResponse) ProtoMessage()    {}
func (*ErrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{4}
}

func (m *ErrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrResponse.Unmarshal(m, b)
}
func (m *ErrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrResponse.Marshal(b, m, deterministic)
}
func (m *ErrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrResponse.Merge(m, src)
}
func (m *ErrResponse) XXX_Size() int {
	return xxx_messageInfo_ErrResponse.Size(m)
}
func (m *ErrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrResponse proto.InternalMessageInfo

func (m *ErrResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ErrResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UploadTicketErr struct {
	//订单 id
	TicketId string `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	//错误信息
	Err                  *ErrResponse `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadTicketErr) Reset()         { *m = UploadTicketErr{} }
func (m *UploadTicketErr) String() string { return proto.CompactTextString(m) }
func (*UploadTicketErr) ProtoMessage()    {}
func (*UploadTicketErr) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{5}
}

func (m *UploadTicketErr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadTicketErr.Unmarshal(m, b)
}
func (m *UploadTicketErr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadTicketErr.Marshal(b, m, deterministic)
}
func (m *UploadTicketErr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadTicketErr.Merge(m, src)
}
func (m *UploadTicketErr) XXX_Size() int {
	return xxx_messageInfo_UploadTicketErr.Size(m)
}
func (m *UploadTicketErr) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadTicketErr.DiscardUnknown(m)
}

var xxx_messageInfo_UploadTicketErr proto.InternalMessageInfo

func (m *UploadTicketErr) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *UploadTicketErr) GetErr() *ErrResponse {
	if m != nil {
		return m.Err
	}
	return nil
}

type UploadTicketRequest struct {
	// (必传)门店id
	StoreId string `protobuf:"bytes,1,opt,name=storeId,proto3" json:"storeId,omitempty"`
	// （必传）pos机id
	PosId string `protobuf:"bytes,2,opt,name=posId,proto3" json:"posId,omitempty"`
	// （必传）完整的ticket信息
	Ticket               *Ticket  `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadTicketRequest) Reset()         { *m = UploadTicketRequest{} }
func (m *UploadTicketRequest) String() string { return proto.CompactTextString(m) }
func (*UploadTicketRequest) ProtoMessage()    {}
func (*UploadTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{6}
}

func (m *UploadTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadTicketRequest.Unmarshal(m, b)
}
func (m *UploadTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadTicketRequest.Marshal(b, m, deterministic)
}
func (m *UploadTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadTicketRequest.Merge(m, src)
}
func (m *UploadTicketRequest) XXX_Size() int {
	return xxx_messageInfo_UploadTicketRequest.Size(m)
}
func (m *UploadTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadTicketRequest proto.InternalMessageInfo

func (m *UploadTicketRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *UploadTicketRequest) GetPosId() string {
	if m != nil {
		return m.PosId
	}
	return ""
}

func (m *UploadTicketRequest) GetTicket() *Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type UploadTicketResponse struct {
	// （必传）是否上传成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息
	UploadErr            *UploadTicketErr `protobuf:"bytes,2,opt,name=uploadErr,proto3" json:"uploadErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadTicketResponse) Reset()         { *m = UploadTicketResponse{} }
func (m *UploadTicketResponse) String() string { return proto.CompactTextString(m) }
func (*UploadTicketResponse) ProtoMessage()    {}
func (*UploadTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{7}
}

func (m *UploadTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadTicketResponse.Unmarshal(m, b)
}
func (m *UploadTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadTicketResponse.Marshal(b, m, deterministic)
}
func (m *UploadTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadTicketResponse.Merge(m, src)
}
func (m *UploadTicketResponse) XXX_Size() int {
	return xxx_messageInfo_UploadTicketResponse.Size(m)
}
func (m *UploadTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadTicketResponse proto.InternalMessageInfo

func (m *UploadTicketResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UploadTicketResponse) GetUploadErr() *UploadTicketErr {
	if m != nil {
		return m.UploadErr
	}
	return nil
}

type UploadTicketBatchRequest struct {
	// (必传)门店id
	StoreId string `protobuf:"bytes,1,opt,name=storeId,proto3" json:"storeId,omitempty"`
	// （必传）pos机id
	PosId string `protobuf:"bytes,2,opt,name=posId,proto3" json:"posId,omitempty"`
	// （必传）订单
	Tickets              []*Ticket `protobuf:"bytes,3,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UploadTicketBatchRequest) Reset()         { *m = UploadTicketBatchRequest{} }
func (m *UploadTicketBatchRequest) String() string { return proto.CompactTextString(m) }
func (*UploadTicketBatchRequest) ProtoMessage()    {}
func (*UploadTicketBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{8}
}

func (m *UploadTicketBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadTicketBatchRequest.Unmarshal(m, b)
}
func (m *UploadTicketBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadTicketBatchRequest.Marshal(b, m, deterministic)
}
func (m *UploadTicketBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadTicketBatchRequest.Merge(m, src)
}
func (m *UploadTicketBatchRequest) XXX_Size() int {
	return xxx_messageInfo_UploadTicketBatchRequest.Size(m)
}
func (m *UploadTicketBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadTicketBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadTicketBatchRequest proto.InternalMessageInfo

func (m *UploadTicketBatchRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *UploadTicketBatchRequest) GetPosId() string {
	if m != nil {
		return m.PosId
	}
	return ""
}

func (m *UploadTicketBatchRequest) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type UploadTicketBatchResponse struct {
	// 是否全部上传成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 上传失败订单的错误信息
	UploadErr            *ErrResponse `protobuf:"bytes,2,opt,name=uploadErr,proto3" json:"uploadErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadTicketBatchResponse) Reset()         { *m = UploadTicketBatchResponse{} }
func (m *UploadTicketBatchResponse) String() string { return proto.CompactTextString(m) }
func (*UploadTicketBatchResponse) ProtoMessage()    {}
func (*UploadTicketBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{9}
}

func (m *UploadTicketBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadTicketBatchResponse.Unmarshal(m, b)
}
func (m *UploadTicketBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadTicketBatchResponse.Marshal(b, m, deterministic)
}
func (m *UploadTicketBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadTicketBatchResponse.Merge(m, src)
}
func (m *UploadTicketBatchResponse) XXX_Size() int {
	return xxx_messageInfo_UploadTicketBatchResponse.Size(m)
}
func (m *UploadTicketBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadTicketBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadTicketBatchResponse proto.InternalMessageInfo

func (m *UploadTicketBatchResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UploadTicketBatchResponse) GetUploadErr() *ErrResponse {
	if m != nil {
		return m.UploadErr
	}
	return nil
}

type GetTicketByIdsRequest struct {
	// （必传）订单id
	TicketIds            []string `protobuf:"bytes,1,rep,name=ticketIds,proto3" json:"ticketIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketByIdsRequest) Reset()         { *m = GetTicketByIdsRequest{} }
func (m *GetTicketByIdsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTicketByIdsRequest) ProtoMessage()    {}
func (*GetTicketByIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{10}
}

func (m *GetTicketByIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketByIdsRequest.Unmarshal(m, b)
}
func (m *GetTicketByIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketByIdsRequest.Marshal(b, m, deterministic)
}
func (m *GetTicketByIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketByIdsRequest.Merge(m, src)
}
func (m *GetTicketByIdsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTicketByIdsRequest.Size(m)
}
func (m *GetTicketByIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketByIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketByIdsRequest proto.InternalMessageInfo

func (m *GetTicketByIdsRequest) GetTicketIds() []string {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

type GetTicketByIdsResponse struct {
	Tickets              []*Ticket    `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Err                  *ErrResponse `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTicketByIdsResponse) Reset()         { *m = GetTicketByIdsResponse{} }
func (m *GetTicketByIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTicketByIdsResponse) ProtoMessage()    {}
func (*GetTicketByIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{11}
}

func (m *GetTicketByIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketByIdsResponse.Unmarshal(m, b)
}
func (m *GetTicketByIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketByIdsResponse.Marshal(b, m, deterministic)
}
func (m *GetTicketByIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketByIdsResponse.Merge(m, src)
}
func (m *GetTicketByIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTicketByIdsResponse.Size(m)
}
func (m *GetTicketByIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketByIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketByIdsResponse proto.InternalMessageInfo

func (m *GetTicketByIdsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *GetTicketByIdsResponse) GetErr() *ErrResponse {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetUploadTicketByStoreIdRequest struct {
	// （必传）门店id
	StoreId string `protobuf:"bytes,1,opt,name=storeId,proto3" json:"storeId,omitempty"`
	// （必传）起始日期
	StartDate string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	// （必传）截止日期
	EndDate              string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadTicketByStoreIdRequest) Reset()         { *m = GetUploadTicketByStoreIdRequest{} }
func (m *GetUploadTicketByStoreIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUploadTicketByStoreIdRequest) ProtoMessage()    {}
func (*GetUploadTicketByStoreIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{12}
}

func (m *GetUploadTicketByStoreIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadTicketByStoreIdRequest.Unmarshal(m, b)
}
func (m *GetUploadTicketByStoreIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadTicketByStoreIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUploadTicketByStoreIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadTicketByStoreIdRequest.Merge(m, src)
}
func (m *GetUploadTicketByStoreIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUploadTicketByStoreIdRequest.Size(m)
}
func (m *GetUploadTicketByStoreIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadTicketByStoreIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadTicketByStoreIdRequest proto.InternalMessageInfo

func (m *GetUploadTicketByStoreIdRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *GetUploadTicketByStoreIdRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *GetUploadTicketByStoreIdRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type GetUploadTicketByStoreIdResponse struct {
	UploadTicketIds      []*GetUploadTicketByStoreIdResponse_DateIds `protobuf:"bytes,1,rep,name=uploadTicketIds,proto3" json:"uploadTicketIds,omitempty"`
	Err                  *ErrResponse                                `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *GetUploadTicketByStoreIdResponse) Reset()         { *m = GetUploadTicketByStoreIdResponse{} }
func (m *GetUploadTicketByStoreIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUploadTicketByStoreIdResponse) ProtoMessage()    {}
func (*GetUploadTicketByStoreIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{13}
}

func (m *GetUploadTicketByStoreIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse.Unmarshal(m, b)
}
func (m *GetUploadTicketByStoreIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUploadTicketByStoreIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadTicketByStoreIdResponse.Merge(m, src)
}
func (m *GetUploadTicketByStoreIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse.Size(m)
}
func (m *GetUploadTicketByStoreIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadTicketByStoreIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadTicketByStoreIdResponse proto.InternalMessageInfo

func (m *GetUploadTicketByStoreIdResponse) GetUploadTicketIds() []*GetUploadTicketByStoreIdResponse_DateIds {
	if m != nil {
		return m.UploadTicketIds
	}
	return nil
}

func (m *GetUploadTicketByStoreIdResponse) GetErr() *ErrResponse {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetUploadTicketByStoreIdResponse_DateIds struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TicketIds            []string `protobuf:"bytes,2,rep,name=ticketIds,proto3" json:"ticketIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadTicketByStoreIdResponse_DateIds) Reset() {
	*m = GetUploadTicketByStoreIdResponse_DateIds{}
}
func (m *GetUploadTicketByStoreIdResponse_DateIds) String() string { return proto.CompactTextString(m) }
func (*GetUploadTicketByStoreIdResponse_DateIds) ProtoMessage()    {}
func (*GetUploadTicketByStoreIdResponse_DateIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{13, 0}
}

func (m *GetUploadTicketByStoreIdResponse_DateIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds.Unmarshal(m, b)
}
func (m *GetUploadTicketByStoreIdResponse_DateIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds.Marshal(b, m, deterministic)
}
func (m *GetUploadTicketByStoreIdResponse_DateIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds.Merge(m, src)
}
func (m *GetUploadTicketByStoreIdResponse_DateIds) XXX_Size() int {
	return xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds.Size(m)
}
func (m *GetUploadTicketByStoreIdResponse_DateIds) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadTicketByStoreIdResponse_DateIds proto.InternalMessageInfo

func (m *GetUploadTicketByStoreIdResponse_DateIds) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *GetUploadTicketByStoreIdResponse_DateIds) GetTicketIds() []string {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

type GetTicketByTicketUNoRequest struct {
	TicketUNos           []string `protobuf:"bytes,1,rep,name=ticketUNos,proto3" json:"ticketUNos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketByTicketUNoRequest) Reset()         { *m = GetTicketByTicketUNoRequest{} }
func (m *GetTicketByTicketUNoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTicketByTicketUNoRequest) ProtoMessage()    {}
func (*GetTicketByTicketUNoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{14}
}

func (m *GetTicketByTicketUNoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketByTicketUNoRequest.Unmarshal(m, b)
}
func (m *GetTicketByTicketUNoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketByTicketUNoRequest.Marshal(b, m, deterministic)
}
func (m *GetTicketByTicketUNoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketByTicketUNoRequest.Merge(m, src)
}
func (m *GetTicketByTicketUNoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTicketByTicketUNoRequest.Size(m)
}
func (m *GetTicketByTicketUNoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketByTicketUNoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketByTicketUNoRequest proto.InternalMessageInfo

func (m *GetTicketByTicketUNoRequest) GetTicketUNos() []string {
	if m != nil {
		return m.TicketUNos
	}
	return nil
}

type GetTicketByTicketUNoResponse struct {
	Tickets              []*Ticket    `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Err                  *ErrResponse `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTicketByTicketUNoResponse) Reset()         { *m = GetTicketByTicketUNoResponse{} }
func (m *GetTicketByTicketUNoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTicketByTicketUNoResponse) ProtoMessage()    {}
func (*GetTicketByTicketUNoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{15}
}

func (m *GetTicketByTicketUNoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketByTicketUNoResponse.Unmarshal(m, b)
}
func (m *GetTicketByTicketUNoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketByTicketUNoResponse.Marshal(b, m, deterministic)
}
func (m *GetTicketByTicketUNoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketByTicketUNoResponse.Merge(m, src)
}
func (m *GetTicketByTicketUNoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTicketByTicketUNoResponse.Size(m)
}
func (m *GetTicketByTicketUNoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketByTicketUNoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketByTicketUNoResponse proto.InternalMessageInfo

func (m *GetTicketByTicketUNoResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *GetTicketByTicketUNoResponse) GetErr() *ErrResponse {
	if m != nil {
		return m.Err
	}
	return nil
}

type AcceptHeyteaNewOrderResponse struct {
	OrdersNo             string   `protobuf:"bytes,1,opt,name=ordersNo,proto3" json:"ordersNo,omitempty"`
	OrdersOuid           string   `protobuf:"bytes,2,opt,name=ordersOuid,proto3" json:"ordersOuid,omitempty"`
	SoOuid               string   `protobuf:"bytes,3,opt,name=soOuid,proto3" json:"soOuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptHeyteaNewOrderResponse) Reset()         { *m = AcceptHeyteaNewOrderResponse{} }
func (m *AcceptHeyteaNewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptHeyteaNewOrderResponse) ProtoMessage()    {}
func (*AcceptHeyteaNewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{16}
}

func (m *AcceptHeyteaNewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptHeyteaNewOrderResponse.Unmarshal(m, b)
}
func (m *AcceptHeyteaNewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptHeyteaNewOrderResponse.Marshal(b, m, deterministic)
}
func (m *AcceptHeyteaNewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptHeyteaNewOrderResponse.Merge(m, src)
}
func (m *AcceptHeyteaNewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptHeyteaNewOrderResponse.Size(m)
}
func (m *AcceptHeyteaNewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptHeyteaNewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptHeyteaNewOrderResponse proto.InternalMessageInfo

func (m *AcceptHeyteaNewOrderResponse) GetOrdersNo() string {
	if m != nil {
		return m.OrdersNo
	}
	return ""
}

func (m *AcceptHeyteaNewOrderResponse) GetOrdersOuid() string {
	if m != nil {
		return m.OrdersOuid
	}
	return ""
}

func (m *AcceptHeyteaNewOrderResponse) GetSoOuid() string {
	if m != nil {
		return m.SoOuid
	}
	return ""
}

type AccpetNewOrderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccpetNewOrderRequest) Reset()         { *m = AccpetNewOrderRequest{} }
func (m *AccpetNewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*AccpetNewOrderRequest) ProtoMessage()    {}
func (*AccpetNewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{17}
}

func (m *AccpetNewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccpetNewOrderRequest.Unmarshal(m, b)
}
func (m *AccpetNewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccpetNewOrderRequest.Marshal(b, m, deterministic)
}
func (m *AccpetNewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccpetNewOrderRequest.Merge(m, src)
}
func (m *AccpetNewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_AccpetNewOrderRequest.Size(m)
}
func (m *AccpetNewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccpetNewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccpetNewOrderRequest proto.InternalMessageInfo

type AcceptNewOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptNewOrderResponse) Reset()         { *m = AcceptNewOrderResponse{} }
func (m *AcceptNewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptNewOrderResponse) ProtoMessage()    {}
func (*AcceptNewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{18}
}

func (m *AcceptNewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptNewOrderResponse.Unmarshal(m, b)
}
func (m *AcceptNewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptNewOrderResponse.Marshal(b, m, deterministic)
}
func (m *AcceptNewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptNewOrderResponse.Merge(m, src)
}
func (m *AcceptNewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptNewOrderResponse.Size(m)
}
func (m *AcceptNewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptNewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptNewOrderResponse proto.InternalMessageInfo

type AcceptCancelOrderRequest struct {
	ShopId               string   `protobuf:"bytes,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	OrdersNo             string   `protobuf:"bytes,2,opt,name=ordersNo,proto3" json:"ordersNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptCancelOrderRequest) Reset()         { *m = AcceptCancelOrderRequest{} }
func (m *AcceptCancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptCancelOrderRequest) ProtoMessage()    {}
func (*AcceptCancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{19}
}

func (m *AcceptCancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptCancelOrderRequest.Unmarshal(m, b)
}
func (m *AcceptCancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptCancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *AcceptCancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptCancelOrderRequest.Merge(m, src)
}
func (m *AcceptCancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptCancelOrderRequest.Size(m)
}
func (m *AcceptCancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptCancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptCancelOrderRequest proto.InternalMessageInfo

func (m *AcceptCancelOrderRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *AcceptCancelOrderRequest) GetOrdersNo() string {
	if m != nil {
		return m.OrdersNo
	}
	return ""
}

type AcceptCancelOrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptCancelOrderResponse) Reset()         { *m = AcceptCancelOrderResponse{} }
func (m *AcceptCancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptCancelOrderResponse) ProtoMessage()    {}
func (*AcceptCancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{20}
}

func (m *AcceptCancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptCancelOrderResponse.Unmarshal(m, b)
}
func (m *AcceptCancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptCancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *AcceptCancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptCancelOrderResponse.Merge(m, src)
}
func (m *AcceptCancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptCancelOrderResponse.Size(m)
}
func (m *AcceptCancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptCancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptCancelOrderResponse proto.InternalMessageInfo

func (m *AcceptCancelOrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateOrderStatusRequest struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderStatusRequest) Reset()         { *m = UpdateOrderStatusRequest{} }
func (m *UpdateOrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusRequest) ProtoMessage()    {}
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{21}
}

func (m *UpdateOrderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusRequest.Unmarshal(m, b)
}
func (m *UpdateOrderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusRequest.Merge(m, src)
}
func (m *UpdateOrderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusRequest.Size(m)
}
func (m *UpdateOrderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusRequest proto.InternalMessageInfo

func (m *UpdateOrderStatusRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *UpdateOrderStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateOrderStatusRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type UpdateOrderStatusReponse struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderStatusReponse) Reset()         { *m = UpdateOrderStatusReponse{} }
func (m *UpdateOrderStatusReponse) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderStatusReponse) ProtoMessage()    {}
func (*UpdateOrderStatusReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{22}
}

func (m *UpdateOrderStatusReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderStatusReponse.Unmarshal(m, b)
}
func (m *UpdateOrderStatusReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderStatusReponse.Marshal(b, m, deterministic)
}
func (m *UpdateOrderStatusReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderStatusReponse.Merge(m, src)
}
func (m *UpdateOrderStatusReponse) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderStatusReponse.Size(m)
}
func (m *UpdateOrderStatusReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderStatusReponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderStatusReponse proto.InternalMessageInfo

func (m *UpdateOrderStatusReponse) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *UpdateOrderStatusReponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateOrderStatusReponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetOrderByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderByIdRequest) Reset()         { *m = GetOrderByIdRequest{} }
func (m *GetOrderByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderByIdRequest) ProtoMessage()    {}
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{23}
}

func (m *GetOrderByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByIdRequest.Unmarshal(m, b)
}
func (m *GetOrderByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByIdRequest.Merge(m, src)
}
func (m *GetOrderByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderByIdRequest.Size(m)
}
func (m *GetOrderByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByIdRequest proto.InternalMessageInfo

func (m *GetOrderByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOrderByStoreRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderByStoreRequest) Reset()         { *m = GetOrderByStoreRequest{} }
func (m *GetOrderByStoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderByStoreRequest) ProtoMessage()    {}
func (*GetOrderByStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{24}
}

func (m *GetOrderByStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByStoreRequest.Unmarshal(m, b)
}
func (m *GetOrderByStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByStoreRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderByStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByStoreRequest.Merge(m, src)
}
func (m *GetOrderByStoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderByStoreRequest.Size(m)
}
func (m *GetOrderByStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByStoreRequest proto.InternalMessageInfo

func (m *GetOrderByStoreRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOrderByStoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderByStoreResponse) Reset()         { *m = GetOrderByStoreResponse{} }
func (m *GetOrderByStoreResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderByStoreResponse) ProtoMessage()    {}
func (*GetOrderByStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{25}
}

func (m *GetOrderByStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByStoreResponse.Unmarshal(m, b)
}
func (m *GetOrderByStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByStoreResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderByStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByStoreResponse.Merge(m, src)
}
func (m *GetOrderByStoreResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderByStoreResponse.Size(m)
}
func (m *GetOrderByStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByStoreResponse proto.InternalMessageInfo

type SyncTakeoutRequest struct {
	PosId                string   `protobuf:"bytes,1,opt,name=posId,proto3" json:"posId,omitempty"`
	StoreId              string   `protobuf:"bytes,2,opt,name=storeId,proto3" json:"storeId,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeStamp            string   `protobuf:"bytes,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	WithDetail           bool     `protobuf:"varint,5,opt,name=WithDetail,proto3" json:"WithDetail,omitempty"`
	WithID               bool     `protobuf:"varint,6,opt,name=WithID,proto3" json:"WithID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTakeoutRequest) Reset()         { *m = SyncTakeoutRequest{} }
func (m *SyncTakeoutRequest) String() string { return proto.CompactTextString(m) }
func (*SyncTakeoutRequest) ProtoMessage()    {}
func (*SyncTakeoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{26}
}

func (m *SyncTakeoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTakeoutRequest.Unmarshal(m, b)
}
func (m *SyncTakeoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTakeoutRequest.Marshal(b, m, deterministic)
}
func (m *SyncTakeoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTakeoutRequest.Merge(m, src)
}
func (m *SyncTakeoutRequest) XXX_Size() int {
	return xxx_messageInfo_SyncTakeoutRequest.Size(m)
}
func (m *SyncTakeoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTakeoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTakeoutRequest proto.InternalMessageInfo

func (m *SyncTakeoutRequest) GetPosId() string {
	if m != nil {
		return m.PosId
	}
	return ""
}

func (m *SyncTakeoutRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *SyncTakeoutRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SyncTakeoutRequest) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *SyncTakeoutRequest) GetWithDetail() bool {
	if m != nil {
		return m.WithDetail
	}
	return false
}

func (m *SyncTakeoutRequest) GetWithID() bool {
	if m != nil {
		return m.WithID
	}
	return false
}

type SyncTakeoutResponse struct {
	TimeStamp            string   `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncTakeoutResponse) Reset()         { *m = SyncTakeoutResponse{} }
func (m *SyncTakeoutResponse) String() string { return proto.CompactTextString(m) }
func (*SyncTakeoutResponse) ProtoMessage()    {}
func (*SyncTakeoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fef0bf6795f16d, []int{27}
}

func (m *SyncTakeoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTakeoutResponse.Unmarshal(m, b)
}
func (m *SyncTakeoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTakeoutResponse.Marshal(b, m, deterministic)
}
func (m *SyncTakeoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTakeoutResponse.Merge(m, src)
}
func (m *SyncTakeoutResponse) XXX_Size() int {
	return xxx_messageInfo_SyncTakeoutResponse.Size(m)
}
func (m *SyncTakeoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTakeoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTakeoutResponse proto.InternalMessageInfo

func (m *SyncTakeoutResponse) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "oms.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "oms.HelloResponse")
	proto.RegisterType((*HealthRequest)(nil), "oms.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "oms.HealthResponse")
	proto.RegisterType((*ErrResponse)(nil), "oms.ErrResponse")
	proto.RegisterType((*UploadTicketErr)(nil), "oms.UploadTicketErr")
	proto.RegisterType((*UploadTicketRequest)(nil), "oms.UploadTicketRequest")
	proto.RegisterType((*UploadTicketResponse)(nil), "oms.UploadTicketResponse")
	proto.RegisterType((*UploadTicketBatchRequest)(nil), "oms.UploadTicketBatchRequest")
	proto.RegisterType((*UploadTicketBatchResponse)(nil), "oms.UploadTicketBatchResponse")
	proto.RegisterType((*GetTicketByIdsRequest)(nil), "oms.GetTicketByIdsRequest")
	proto.RegisterType((*GetTicketByIdsResponse)(nil), "oms.GetTicketByIdsResponse")
	proto.RegisterType((*GetUploadTicketByStoreIdRequest)(nil), "oms.GetUploadTicketByStoreIdRequest")
	proto.RegisterType((*GetUploadTicketByStoreIdResponse)(nil), "oms.GetUploadTicketByStoreIdResponse")
	proto.RegisterType((*GetUploadTicketByStoreIdResponse_DateIds)(nil), "oms.GetUploadTicketByStoreIdResponse.DateIds")
	proto.RegisterType((*GetTicketByTicketUNoRequest)(nil), "oms.GetTicketByTicketUNoRequest")
	proto.RegisterType((*GetTicketByTicketUNoResponse)(nil), "oms.GetTicketByTicketUNoResponse")
	proto.RegisterType((*AcceptHeyteaNewOrderResponse)(nil), "oms.AcceptHeyteaNewOrderResponse")
	proto.RegisterType((*AccpetNewOrderRequest)(nil), "oms.AccpetNewOrderRequest")
	proto.RegisterType((*AcceptNewOrderResponse)(nil), "oms.AcceptNewOrderResponse")
	proto.RegisterType((*AcceptCancelOrderRequest)(nil), "oms.AcceptCancelOrderRequest")
	proto.RegisterType((*AcceptCancelOrderResponse)(nil), "oms.AcceptCancelOrderResponse")
	proto.RegisterType((*UpdateOrderStatusRequest)(nil), "oms.UpdateOrderStatusRequest")
	proto.RegisterType((*UpdateOrderStatusReponse)(nil), "oms.UpdateOrderStatusReponse")
	proto.RegisterType((*GetOrderByIdRequest)(nil), "oms.GetOrderByIdRequest")
	proto.RegisterType((*GetOrderByStoreRequest)(nil), "oms.GetOrderByStoreRequest")
	proto.RegisterType((*GetOrderByStoreResponse)(nil), "oms.GetOrderByStoreResponse")
	proto.RegisterType((*SyncTakeoutRequest)(nil), "oms.SyncTakeoutRequest")
	proto.RegisterType((*SyncTakeoutResponse)(nil), "oms.SyncTakeoutResponse")
}

func init() { proto.RegisterFile("proto/oms/oms.proto", fileDescriptor_61fef0bf6795f16d) }

var fileDescriptor_61fef0bf6795f16d = []byte{
	// 1153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4b, 0x4f, 0x23, 0x47,
	0x10, 0xd6, 0xd8, 0xcb, 0xab, 0x4c, 0x78, 0xb4, 0x59, 0x18, 0x0f, 0x5e, 0x1e, 0xbd, 0x90, 0x10,
	0xa4, 0x60, 0x09, 0xb4, 0x97, 0x8d, 0x72, 0xd8, 0x2c, 0x88, 0xe5, 0x10, 0x50, 0xcc, 0xa2, 0x3d,
	0xcf, 0xce, 0xf4, 0xe2, 0x09, 0xb6, 0x7b, 0x76, 0xba, 0x9d, 0xc4, 0x59, 0xe5, 0x92, 0x43, 0xce,
	0x91, 0xf2, 0x47, 0xf2, 0x57, 0xa2, 0x5c, 0x73, 0xcc, 0x0f, 0x89, 0xfa, 0x35, 0xee, 0x79, 0x61,
	0x12, 0xed, 0x01, 0x31, 0xd5, 0xd5, 0x55, 0x5f, 0x55, 0x75, 0xd7, 0x57, 0x6d, 0x68, 0xc6, 0x09,
	0xe5, 0xb4, 0x43, 0x07, 0x4c, 0xfc, 0x1d, 0x49, 0x09, 0xd5, 0xe9, 0x80, 0x79, 0xeb, 0x13, 0x0d,
	0x8f, 0x82, 0x3b, 0xc2, 0x95, 0xd2, 0x6b, 0xdf, 0x52, 0x7a, 0xdb, 0x27, 0x1d, 0x3f, 0x8e, 0x3a,
	0xfe, 0x70, 0x48, 0xb9, 0xcf, 0x23, 0x3a, 0xd4, 0xa6, 0xde, 0x86, 0x65, 0xe5, 0xdf, 0x11, 0x3a,
	0xd2, 0x66, 0x18, 0xc3, 0xe2, 0x2b, 0xd2, 0xef, 0xd3, 0x2e, 0x79, 0x3f, 0x22, 0x8c, 0x23, 0x04,
	0x8f, 0xf8, 0x38, 0x26, 0xae, 0xb3, 0xe3, 0x1c, 0x2c, 0x74, 0xe5, 0x37, 0xde, 0x85, 0x4f, 0xf4,
	0x1e, 0x16, 0xd3, 0x21, 0x23, 0x68, 0x05, 0xea, 0x03, 0x76, 0xab, 0xf7, 0x88, 0x4f, 0xbc, 0x2c,
	0xb6, 0xf8, 0x7d, 0xde, 0xd3, 0x7e, 0xf0, 0x0a, 0x2c, 0x99, 0x05, 0x65, 0x84, 0x4f, 0xa0, 0x71,
	0x96, 0x24, 0xa9, 0x8f, 0x12, 0x20, 0xe3, 0xb7, 0x36, 0xf1, 0xfb, 0x2d, 0x2c, 0xdf, 0xc4, 0x7d,
	0xea, 0x87, 0xaf, 0x65, 0xae, 0x67, 0x49, 0x82, 0x3c, 0x98, 0x57, 0x89, 0x5f, 0x84, 0xda, 0x38,
	0x95, 0x11, 0x86, 0x3a, 0x49, 0x12, 0xe9, 0xa0, 0x71, 0xbc, 0x72, 0x24, 0x4a, 0x67, 0x61, 0x76,
	0x85, 0x12, 0x7f, 0x07, 0x4d, 0xdb, 0xa5, 0x49, 0xdc, 0x85, 0x39, 0xc6, 0x69, 0x42, 0x52, 0xaf,
	0x46, 0x44, 0x6b, 0x30, 0x13, 0x53, 0x76, 0x11, 0xea, 0xb8, 0x94, 0x80, 0x9e, 0xc2, 0xac, 0x82,
	0x75, 0xeb, 0x12, 0xad, 0x21, 0xd1, 0xb4, 0x4f, 0xad, 0xc2, 0x21, 0xac, 0x65, 0xb1, 0x74, 0xf2,
	0x02, 0x6c, 0x14, 0x04, 0x84, 0x31, 0x09, 0x36, 0xdf, 0x35, 0x22, 0x3a, 0x86, 0x85, 0x91, 0xb4,
	0x38, 0x4b, 0xf3, 0x58, 0x93, 0x9e, 0x73, 0x65, 0xe8, 0x4e, 0xb6, 0xe1, 0xf7, 0xe0, 0xda, 0xda,
	0xaf, 0x7d, 0x1e, 0xf4, 0xfe, 0x6f, 0x5a, 0xfb, 0x30, 0xa7, 0x62, 0x67, 0x6e, 0x7d, 0xa7, 0x9e,
	0xcf, 0xcb, 0xe8, 0x30, 0x81, 0x56, 0x09, 0xe4, 0xd4, 0xec, 0x8e, 0x8a, 0xd9, 0x15, 0x4f, 0xc9,
	0xca, 0xec, 0x19, 0x3c, 0x3e, 0x27, 0x5c, 0x63, 0x8c, 0x2f, 0x42, 0x66, 0xd2, 0x6a, 0xc3, 0x82,
	0x39, 0x74, 0x01, 0x52, 0x3f, 0x58, 0xe8, 0x4e, 0x16, 0x70, 0x00, 0xeb, 0x79, 0x33, 0x1d, 0x9a,
	0x95, 0x9e, 0x53, 0x9d, 0xde, 0x83, 0xee, 0x11, 0x83, 0xed, 0x73, 0xc2, 0x33, 0x55, 0x18, 0x5f,
	0xab, 0xda, 0x4e, 0x2f, 0x7e, 0x1b, 0x16, 0x18, 0xf7, 0x13, 0x7e, 0xea, 0x73, 0xa2, 0x0f, 0x60,
	0xb2, 0x20, 0xec, 0xc8, 0x30, 0x94, 0xba, 0xba, 0xb2, 0xd3, 0x22, 0xfe, 0xdb, 0x81, 0x9d, 0x6a,
	0x54, 0x9d, 0xe4, 0x1b, 0x58, 0x1e, 0x59, 0x1b, 0x4c, 0x89, 0x1a, 0xc7, 0x5f, 0xc8, 0x4c, 0xa6,
	0xd9, 0x1f, 0x09, 0x24, 0x51, 0xb4, 0xbc, 0x97, 0x87, 0x94, 0xc5, 0xfb, 0x12, 0xe6, 0xb4, 0xbd,
	0x68, 0xf1, 0x50, 0xe4, 0xa0, 0x5b, 0x5c, 0x7c, 0x67, 0x0f, 0xae, 0x96, 0x3f, 0xb8, 0xaf, 0x60,
	0xd3, 0x3a, 0x38, 0xf5, 0xff, 0xe6, 0x32, 0x25, 0xa7, 0x2d, 0x00, 0x6e, 0xd6, 0xcc, 0xb1, 0x5b,
	0x2b, 0x38, 0x82, 0x76, 0xb9, 0xf9, 0xc7, 0x3f, 0xfd, 0x04, 0xda, 0x2f, 0x82, 0x80, 0xc4, 0xfc,
	0x15, 0x19, 0x73, 0xe2, 0x5f, 0x92, 0x1f, 0xae, 0x92, 0x90, 0x4c, 0xe8, 0xcd, 0x83, 0x79, 0x2a,
	0x16, 0xd8, 0x25, 0x35, 0x2c, 0x65, 0x64, 0x91, 0x86, 0xfa, 0xbe, 0x1a, 0x45, 0xa6, 0xfd, 0xac,
	0x15, 0xb4, 0x0e, 0xb3, 0x8c, 0x4a, 0x9d, 0x3a, 0x7d, 0x2d, 0xe1, 0x0d, 0x78, 0xfc, 0x22, 0x08,
	0x62, 0xc2, 0x27, 0x68, 0x8a, 0x6c, 0x5d, 0x58, 0x57, 0xc1, 0xe4, 0xc3, 0xc0, 0x97, 0xe0, 0x2a,
	0xcd, 0x4b, 0x7f, 0x18, 0x90, 0xbe, 0x6d, 0x25, 0x61, 0x7a, 0x34, 0x4e, 0x2f, 0xa7, 0x96, 0x32,
	0xa1, 0xd7, 0xb2, 0xa1, 0xe3, 0x67, 0xd0, 0x2a, 0xf1, 0x37, 0xad, 0xef, 0xf1, 0x3b, 0xc1, 0x50,
	0xe2, 0xfc, 0xa5, 0xc1, 0x35, 0xf7, 0xf9, 0x28, 0x6d, 0xe5, 0xfb, 0xf8, 0x5c, 0x84, 0x28, 0x37,
	0xeb, 0x40, 0xb4, 0x24, 0xd6, 0xfd, 0x40, 0xcc, 0x37, 0x53, 0x21, 0x25, 0xe1, 0x5e, 0x29, 0x4e,
	0x7a, 0x22, 0xff, 0x19, 0xc7, 0xca, 0xa8, 0x9e, 0xcd, 0x68, 0x1f, 0x9a, 0xe7, 0x84, 0x4b, 0x18,
	0xc1, 0x30, 0x26, 0x99, 0x25, 0xa8, 0x45, 0xc6, 0x7d, 0x2d, 0x0a, 0xf1, 0x81, 0x64, 0x22, 0xbd,
	0x4d, 0xf6, 0x59, 0xd5, 0xce, 0x16, 0x6c, 0x14, 0x76, 0xea, 0x43, 0xfc, 0xc3, 0x01, 0x74, 0x3d,
	0x1e, 0x06, 0xaf, 0xd5, 0xe4, 0x36, 0x1e, 0x52, 0x02, 0x77, 0x6c, 0x02, 0xb7, 0x38, 0xa7, 0x56,
	0x20, 0xfc, 0x7e, 0x34, 0x88, 0xd4, 0xc0, 0x9a, 0xe9, 0x2a, 0x41, 0x35, 0xe4, 0x80, 0x5c, 0x73,
	0x7f, 0x10, 0xbb, 0x8f, 0x14, 0x13, 0xa5, 0x0b, 0xe2, 0xaa, 0xbe, 0x89, 0x78, 0xef, 0x94, 0x70,
	0x3f, 0xea, 0xbb, 0x33, 0xb2, 0x06, 0xd6, 0x8a, 0x28, 0x9c, 0x90, 0x2e, 0x4e, 0xdd, 0x59, 0xa9,
	0xd3, 0x12, 0x3e, 0x81, 0x66, 0x26, 0x62, 0x7d, 0x43, 0x32, 0x60, 0x4e, 0x0e, 0xec, 0xf8, 0x4f,
	0x80, 0xfa, 0xd5, 0x80, 0xa1, 0x2b, 0x68, 0xc8, 0xf7, 0xc6, 0x37, 0x84, 0xf7, 0x68, 0x88, 0x56,
	0x65, 0x07, 0xda, 0xaf, 0x14, 0x0f, 0xd9, 0x4b, 0xba, 0x4a, 0xad, 0x5f, 0xfe, 0xfa, 0xe7, 0xf7,
	0x5a, 0x13, 0xad, 0xca, 0x27, 0xd0, 0xf7, 0xc7, 0xf2, 0xb1, 0xd3, 0x13, 0x5b, 0x50, 0x57, 0x38,
	0x14, 0x8f, 0x91, 0x97, 0x3d, 0x12, 0xdc, 0x21, 0x63, 0x6d, 0xbd, 0x57, 0xbc, 0x66, 0x66, 0x4d,
	0xbb, 0xf4, 0xa4, 0xcb, 0x35, 0x84, 0xb2, 0x2e, 0xc5, 0x1e, 0x14, 0xc0, 0xa2, 0xcd, 0xa2, 0xc8,
	0x2d, 0x4c, 0x69, 0xe3, 0xba, 0x55, 0xa2, 0xd1, 0x00, 0x5b, 0x12, 0xc0, 0xc5, 0x4d, 0x1b, 0x40,
	0xd3, 0xd0, 0x73, 0xe7, 0x10, 0xfd, 0x08, 0xab, 0x85, 0x31, 0x8b, 0x9e, 0x14, 0xfc, 0xd9, 0x13,
	0xdf, 0xdb, 0xaa, 0x52, 0x6b, 0xcc, 0x3d, 0x89, 0xb9, 0x85, 0x5b, 0x25, 0x98, 0x9d, 0xb7, 0x62,
	0xab, 0x40, 0x66, 0xb0, 0x94, 0x1d, 0xa1, 0xc8, 0x33, 0xc3, 0xa3, 0x38, 0x8e, 0xbd, 0xcd, 0x52,
	0x9d, 0x06, 0x3c, 0x90, 0x80, 0x18, 0x3f, 0x29, 0x03, 0x4c, 0xb9, 0x5f, 0x80, 0xfe, 0xe6, 0x80,
	0x5b, 0x35, 0x9d, 0xd0, 0xde, 0x94, 0xe1, 0xa5, 0x22, 0xd9, 0x7f, 0xd0, 0x88, 0xc3, 0x9f, 0xc9,
	0x98, 0x76, 0x71, 0xdb, 0x8e, 0x49, 0x36, 0x0a, 0xeb, 0x7c, 0xd0, 0x0d, 0xf3, 0xb3, 0x08, 0xe9,
	0x57, 0x07, 0xd6, 0xca, 0x66, 0x0a, 0xda, 0xc9, 0xa7, 0x9c, 0x9f, 0x56, 0xde, 0xee, 0x3d, 0x3b,
	0x74, 0x18, 0x9f, 0xcb, 0x30, 0x9e, 0xe2, 0xad, 0xea, 0xd2, 0xdc, 0x0c, 0xa9, 0xac, 0xcd, 0x4f,
	0xb0, 0x5a, 0x60, 0x5e, 0x7d, 0x15, 0xaa, 0x18, 0x5e, 0x5f, 0x85, 0x4a, 0xc2, 0xc6, 0x9f, 0x4a,
	0xf8, 0x1d, 0xbc, 0x99, 0x81, 0x57, 0x3d, 0xcb, 0x3a, 0x81, 0xb4, 0x10, 0xd8, 0x63, 0x71, 0x0d,
	0x73, 0xb4, 0x9a, 0x5e, 0xc3, 0x72, 0x5a, 0xf7, 0x2a, 0xd5, 0x0f, 0x81, 0x56, 0xf4, 0xab, 0xee,
	0xe1, 0x72, 0x8e, 0x16, 0x51, 0x7a, 0xd9, 0x4a, 0x68, 0xd5, 0x6b, 0x97, 0x2b, 0x75, 0xc2, 0xfb,
	0x12, 0x75, 0x1b, 0x7b, 0x15, 0xa8, 0x34, 0x21, 0x02, 0xd4, 0x87, 0x45, 0x9b, 0xdc, 0x75, 0x6f,
	0x97, 0xf0, 0xbd, 0x67, 0x3f, 0x20, 0xf0, 0xa1, 0xf4, 0xbe, 0x87, 0xb7, 0x4b, 0xbd, 0xcb, 0x19,
	0xda, 0xf9, 0x10, 0xa9, 0x7b, 0xf5, 0x0e, 0x1a, 0x16, 0x41, 0xa2, 0x0d, 0xe9, 0xa7, 0x48, 0xf2,
	0x9e, 0x5b, 0x54, 0xdc, 0xdb, 0xc7, 0x69, 0x2e, 0xe3, 0x61, 0xf0, 0xdc, 0x39, 0x7c, 0x3b, 0x2b,
	0x7f, 0xe6, 0x9d, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x65, 0xf3, 0xd9, 0x31, 0x51, 0x0e, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OmsClient is the client API for Oms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OmsClient interface {
	HelloMethod(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	//健康检查
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	//上传订单
	UploadTicket(ctx context.Context, in *UploadTicketRequest, opts ...grpc.CallOption) (*UploadTicketResponse, error)
	//批量上传订单
	UploadTicketBatch(ctx context.Context, in *UploadTicketBatchRequest, opts ...grpc.CallOption) (*UploadTicketBatchResponse, error)
	//根据id获取订单
	GetTicketByIds(ctx context.Context, in *GetTicketByIdsRequest, opts ...grpc.CallOption) (*GetTicketByIdsResponse, error)
	//根据门店和起止日期获得已经上传的订单
	GetUploadTicketByStoreId(ctx context.Context, in *GetUploadTicketByStoreIdRequest, opts ...grpc.CallOption) (*GetUploadTicketByStoreIdResponse, error)
	GetTicketByTicketUNo(ctx context.Context, in *GetTicketByTicketUNoRequest, opts ...grpc.CallOption) (*GetTicketByTicketUNoResponse, error)
	AcceptCancelOrder(ctx context.Context, in *AcceptCancelOrderRequest, opts ...grpc.CallOption) (*AcceptCancelOrderResponse, error)
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusReponse, error)
	GetOrderByStore(ctx context.Context, in *GetOrderByStoreRequest, opts ...grpc.CallOption) (*GetOrderByStoreResponse, error)
	GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Ticket, error)
	SyncTakeout(ctx context.Context, in *SyncTakeoutRequest, opts ...grpc.CallOption) (*SyncTakeoutResponse, error)
}

type omsClient struct {
	cc *grpc.ClientConn
}

func NewOmsClient(cc *grpc.ClientConn) OmsClient {
	return &omsClient{cc}
}

func (c *omsClient) HelloMethod(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/HelloMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) UploadTicket(ctx context.Context, in *UploadTicketRequest, opts ...grpc.CallOption) (*UploadTicketResponse, error) {
	out := new(UploadTicketResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/UploadTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) UploadTicketBatch(ctx context.Context, in *UploadTicketBatchRequest, opts ...grpc.CallOption) (*UploadTicketBatchResponse, error) {
	out := new(UploadTicketBatchResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/UploadTicketBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) GetTicketByIds(ctx context.Context, in *GetTicketByIdsRequest, opts ...grpc.CallOption) (*GetTicketByIdsResponse, error) {
	out := new(GetTicketByIdsResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/GetTicketByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) GetUploadTicketByStoreId(ctx context.Context, in *GetUploadTicketByStoreIdRequest, opts ...grpc.CallOption) (*GetUploadTicketByStoreIdResponse, error) {
	out := new(GetUploadTicketByStoreIdResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/GetUploadTicketByStoreId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) GetTicketByTicketUNo(ctx context.Context, in *GetTicketByTicketUNoRequest, opts ...grpc.CallOption) (*GetTicketByTicketUNoResponse, error) {
	out := new(GetTicketByTicketUNoResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/GetTicketByTicketUNo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) AcceptCancelOrder(ctx context.Context, in *AcceptCancelOrderRequest, opts ...grpc.CallOption) (*AcceptCancelOrderResponse, error) {
	out := new(AcceptCancelOrderResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/AcceptCancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusReponse, error) {
	out := new(UpdateOrderStatusReponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/UpdateOrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) GetOrderByStore(ctx context.Context, in *GetOrderByStoreRequest, opts ...grpc.CallOption) (*GetOrderByStoreResponse, error) {
	out := new(GetOrderByStoreResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/GetOrderByStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Ticket, error) {
	out := new(Ticket)
	err := c.cc.Invoke(ctx, "/oms.Oms/GetOrderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) SyncTakeout(ctx context.Context, in *SyncTakeoutRequest, opts ...grpc.CallOption) (*SyncTakeoutResponse, error) {
	out := new(SyncTakeoutResponse)
	err := c.cc.Invoke(ctx, "/oms.Oms/SyncTakeout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmsServer is the server API for Oms service.
type OmsServer interface {
	HelloMethod(context.Context, *HelloRequest) (*HelloResponse, error)
	//健康检查
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	//上传订单
	UploadTicket(context.Context, *UploadTicketRequest) (*UploadTicketResponse, error)
	//批量上传订单
	UploadTicketBatch(context.Context, *UploadTicketBatchRequest) (*UploadTicketBatchResponse, error)
	//根据id获取订单
	GetTicketByIds(context.Context, *GetTicketByIdsRequest) (*GetTicketByIdsResponse, error)
	//根据门店和起止日期获得已经上传的订单
	GetUploadTicketByStoreId(context.Context, *GetUploadTicketByStoreIdRequest) (*GetUploadTicketByStoreIdResponse, error)
	GetTicketByTicketUNo(context.Context, *GetTicketByTicketUNoRequest) (*GetTicketByTicketUNoResponse, error)
	AcceptCancelOrder(context.Context, *AcceptCancelOrderRequest) (*AcceptCancelOrderResponse, error)
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusReponse, error)
	GetOrderByStore(context.Context, *GetOrderByStoreRequest) (*GetOrderByStoreResponse, error)
	GetOrderById(context.Context, *GetOrderByIdRequest) (*Ticket, error)
	SyncTakeout(context.Context, *SyncTakeoutRequest) (*SyncTakeoutResponse, error)
}

// UnimplementedOmsServer can be embedded to have forward compatible implementations.
type UnimplementedOmsServer struct {
}

func (*UnimplementedOmsServer) HelloMethod(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloMethod not implemented")
}
func (*UnimplementedOmsServer) HealthCheck(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedOmsServer) UploadTicket(ctx context.Context, req *UploadTicketRequest) (*UploadTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadTicket not implemented")
}
func (*UnimplementedOmsServer) UploadTicketBatch(ctx context.Context, req *UploadTicketBatchRequest) (*UploadTicketBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadTicketBatch not implemented")
}
func (*UnimplementedOmsServer) GetTicketByIds(ctx context.Context, req *GetTicketByIdsRequest) (*GetTicketByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicketByIds not implemented")
}
func (*UnimplementedOmsServer) GetUploadTicketByStoreId(ctx context.Context, req *GetUploadTicketByStoreIdRequest) (*GetUploadTicketByStoreIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadTicketByStoreId not implemented")
}
func (*UnimplementedOmsServer) GetTicketByTicketUNo(ctx context.Context, req *GetTicketByTicketUNoRequest) (*GetTicketByTicketUNoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicketByTicketUNo not implemented")
}
func (*UnimplementedOmsServer) AcceptCancelOrder(ctx context.Context, req *AcceptCancelOrderRequest) (*AcceptCancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptCancelOrder not implemented")
}
func (*UnimplementedOmsServer) UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusRequest) (*UpdateOrderStatusReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (*UnimplementedOmsServer) GetOrderByStore(ctx context.Context, req *GetOrderByStoreRequest) (*GetOrderByStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByStore not implemented")
}
func (*UnimplementedOmsServer) GetOrderById(ctx context.Context, req *GetOrderByIdRequest) (*Ticket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderById not implemented")
}
func (*UnimplementedOmsServer) SyncTakeout(ctx context.Context, req *SyncTakeoutRequest) (*SyncTakeoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTakeout not implemented")
}

func RegisterOmsServer(s *grpc.Server, srv OmsServer) {
	s.RegisterService(&_Oms_serviceDesc, srv)
}

func _Oms_HelloMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).HelloMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/HelloMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).HelloMethod(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_UploadTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).UploadTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/UploadTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).UploadTicket(ctx, req.(*UploadTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_UploadTicketBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTicketBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).UploadTicketBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/UploadTicketBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).UploadTicketBatch(ctx, req.(*UploadTicketBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_GetTicketByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).GetTicketByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/GetTicketByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).GetTicketByIds(ctx, req.(*GetTicketByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_GetUploadTicketByStoreId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadTicketByStoreIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).GetUploadTicketByStoreId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/GetUploadTicketByStoreId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).GetUploadTicketByStoreId(ctx, req.(*GetUploadTicketByStoreIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_GetTicketByTicketUNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketByTicketUNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).GetTicketByTicketUNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/GetTicketByTicketUNo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).GetTicketByTicketUNo(ctx, req.(*GetTicketByTicketUNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_AcceptCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptCancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).AcceptCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/AcceptCancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).AcceptCancelOrder(ctx, req.(*AcceptCancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/UpdateOrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_GetOrderByStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).GetOrderByStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/GetOrderByStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).GetOrderByStore(ctx, req.(*GetOrderByStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_GetOrderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).GetOrderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/GetOrderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).GetOrderById(ctx, req.(*GetOrderByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_SyncTakeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTakeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).SyncTakeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oms.Oms/SyncTakeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).SyncTakeout(ctx, req.(*SyncTakeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oms.Oms",
	HandlerType: (*OmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloMethod",
			Handler:    _Oms_HelloMethod_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Oms_HealthCheck_Handler,
		},
		{
			MethodName: "UploadTicket",
			Handler:    _Oms_UploadTicket_Handler,
		},
		{
			MethodName: "UploadTicketBatch",
			Handler:    _Oms_UploadTicketBatch_Handler,
		},
		{
			MethodName: "GetTicketByIds",
			Handler:    _Oms_GetTicketByIds_Handler,
		},
		{
			MethodName: "GetUploadTicketByStoreId",
			Handler:    _Oms_GetUploadTicketByStoreId_Handler,
		},
		{
			MethodName: "GetTicketByTicketUNo",
			Handler:    _Oms_GetTicketByTicketUNo_Handler,
		},
		{
			MethodName: "AcceptCancelOrder",
			Handler:    _Oms_AcceptCancelOrder_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _Oms_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "GetOrderByStore",
			Handler:    _Oms_GetOrderByStore_Handler,
		},
		{
			MethodName: "GetOrderById",
			Handler:    _Oms_GetOrderById_Handler,
		},
		{
			MethodName: "SyncTakeout",
			Handler:    _Oms_SyncTakeout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oms/oms.proto",
}
