// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/oms/takeout.proto

package oms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeyteaTakeout struct {
	CompanyPuid          string             `protobuf:"bytes,1,opt,name=companyPuid,proto3" json:"companyPuid,omitempty"`
	Consumerkey          string             `protobuf:"bytes,2,opt,name=consumerkey,proto3" json:"consumerkey,omitempty"`
	Data                 *HeyteaTakeoutData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HeyteaTakeout) Reset()         { *m = HeyteaTakeout{} }
func (m *HeyteaTakeout) String() string { return proto.CompactTextString(m) }
func (*HeyteaTakeout) ProtoMessage()    {}
func (*HeyteaTakeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{0}
}

func (m *HeyteaTakeout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaTakeout.Unmarshal(m, b)
}
func (m *HeyteaTakeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaTakeout.Marshal(b, m, deterministic)
}
func (m *HeyteaTakeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaTakeout.Merge(m, src)
}
func (m *HeyteaTakeout) XXX_Size() int {
	return xxx_messageInfo_HeyteaTakeout.Size(m)
}
func (m *HeyteaTakeout) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaTakeout.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaTakeout proto.InternalMessageInfo

func (m *HeyteaTakeout) GetCompanyPuid() string {
	if m != nil {
		return m.CompanyPuid
	}
	return ""
}

func (m *HeyteaTakeout) GetConsumerkey() string {
	if m != nil {
		return m.Consumerkey
	}
	return ""
}

func (m *HeyteaTakeout) GetData() *HeyteaTakeoutData {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeyteaTakeoutData struct {
	OrdersNo            string               `protobuf:"bytes,1,opt,name=ordersNo,proto3" json:"ordersNo,omitempty"`
	ShopId              string               `protobuf:"bytes,2,opt,name=shopId,proto3" json:"shopId,omitempty"`
	OrdersSeq           string               `protobuf:"bytes,3,opt,name=ordersSeq,proto3" json:"ordersSeq,omitempty"`
	OrdersTime          string               `protobuf:"bytes,4,opt,name=ordersTime,proto3" json:"ordersTime,omitempty"`
	OrdersStatus        string               `protobuf:"bytes,5,opt,name=ordersStatus,proto3" json:"ordersStatus,omitempty"`
	ExpectTime          string               `protobuf:"bytes,6,opt,name=expectTime,proto3" json:"expectTime,omitempty"`
	PosOuid             string               `protobuf:"bytes,7,opt,name=posOuid,proto3" json:"posOuid,omitempty"`
	DeliverType         string               `protobuf:"bytes,8,opt,name=deliverType,proto3" json:"deliverType,omitempty"`
	TotalAmount         string               `protobuf:"bytes,9,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PaidStatus          string               `protobuf:"bytes,10,opt,name=paidStatus,proto3" json:"paidStatus,omitempty"`
	PaidAmount          string               `protobuf:"bytes,11,opt,name=paidAmount,proto3" json:"paidAmount,omitempty"`
	CustomerRefNo       string               `protobuf:"bytes,13,opt,name=customerRefNo,proto3" json:"customerRefNo,omitempty"`
	OrderLinkType       string               `protobuf:"bytes,14,opt,name=orderLinkType,proto3" json:"orderLinkType,omitempty"`
	PartnerPlatformId   string               `protobuf:"bytes,15,opt,name=partnerPlatformId,proto3" json:"partnerPlatformId,omitempty"`
	PartnerPlatformName string               `protobuf:"bytes,16,opt,name=partnerPlatformName,proto3" json:"partnerPlatformName,omitempty"`
	Memo                string               `protobuf:"bytes,17,opt,name=memo,proto3" json:"memo,omitempty"`
	Takeaway            *HeyteaTakeaway      `protobuf:"bytes,18,opt,name=takeaway,proto3" json:"takeaway,omitempty"`
	Items               []*HeyteaProductItem `protobuf:"bytes,19,rep,name=items,proto3" json:"items,omitempty"`
	Fees                []*HeyteaFee         `protobuf:"bytes,20,rep,name=fees,proto3" json:"fees,omitempty"`
	Promos              []*HeyteaPromotion   `protobuf:"bytes,21,rep,name=promos,proto3" json:"promos,omitempty"`
	// 下单时间
	OrdersTimestamp int64 `protobuf:"varint,22,opt,name=ordersTimestamp,proto3" json:"ordersTimestamp,omitempty"`
	// 期望送达时间
	ExpectTimestamp      int64    `protobuf:"varint,23,opt,name=expectTimestamp,proto3" json:"expectTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaTakeoutData) Reset()         { *m = HeyteaTakeoutData{} }
func (m *HeyteaTakeoutData) String() string { return proto.CompactTextString(m) }
func (*HeyteaTakeoutData) ProtoMessage()    {}
func (*HeyteaTakeoutData) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{1}
}

func (m *HeyteaTakeoutData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaTakeoutData.Unmarshal(m, b)
}
func (m *HeyteaTakeoutData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaTakeoutData.Marshal(b, m, deterministic)
}
func (m *HeyteaTakeoutData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaTakeoutData.Merge(m, src)
}
func (m *HeyteaTakeoutData) XXX_Size() int {
	return xxx_messageInfo_HeyteaTakeoutData.Size(m)
}
func (m *HeyteaTakeoutData) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaTakeoutData.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaTakeoutData proto.InternalMessageInfo

func (m *HeyteaTakeoutData) GetOrdersNo() string {
	if m != nil {
		return m.OrdersNo
	}
	return ""
}

func (m *HeyteaTakeoutData) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *HeyteaTakeoutData) GetOrdersSeq() string {
	if m != nil {
		return m.OrdersSeq
	}
	return ""
}

func (m *HeyteaTakeoutData) GetOrdersTime() string {
	if m != nil {
		return m.OrdersTime
	}
	return ""
}

func (m *HeyteaTakeoutData) GetOrdersStatus() string {
	if m != nil {
		return m.OrdersStatus
	}
	return ""
}

func (m *HeyteaTakeoutData) GetExpectTime() string {
	if m != nil {
		return m.ExpectTime
	}
	return ""
}

func (m *HeyteaTakeoutData) GetPosOuid() string {
	if m != nil {
		return m.PosOuid
	}
	return ""
}

func (m *HeyteaTakeoutData) GetDeliverType() string {
	if m != nil {
		return m.DeliverType
	}
	return ""
}

func (m *HeyteaTakeoutData) GetTotalAmount() string {
	if m != nil {
		return m.TotalAmount
	}
	return ""
}

func (m *HeyteaTakeoutData) GetPaidStatus() string {
	if m != nil {
		return m.PaidStatus
	}
	return ""
}

func (m *HeyteaTakeoutData) GetPaidAmount() string {
	if m != nil {
		return m.PaidAmount
	}
	return ""
}

func (m *HeyteaTakeoutData) GetCustomerRefNo() string {
	if m != nil {
		return m.CustomerRefNo
	}
	return ""
}

func (m *HeyteaTakeoutData) GetOrderLinkType() string {
	if m != nil {
		return m.OrderLinkType
	}
	return ""
}

func (m *HeyteaTakeoutData) GetPartnerPlatformId() string {
	if m != nil {
		return m.PartnerPlatformId
	}
	return ""
}

func (m *HeyteaTakeoutData) GetPartnerPlatformName() string {
	if m != nil {
		return m.PartnerPlatformName
	}
	return ""
}

func (m *HeyteaTakeoutData) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *HeyteaTakeoutData) GetTakeaway() *HeyteaTakeaway {
	if m != nil {
		return m.Takeaway
	}
	return nil
}

func (m *HeyteaTakeoutData) GetItems() []*HeyteaProductItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *HeyteaTakeoutData) GetFees() []*HeyteaFee {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *HeyteaTakeoutData) GetPromos() []*HeyteaPromotion {
	if m != nil {
		return m.Promos
	}
	return nil
}

func (m *HeyteaTakeoutData) GetOrdersTimestamp() int64 {
	if m != nil {
		return m.OrdersTimestamp
	}
	return 0
}

func (m *HeyteaTakeoutData) GetExpectTimestamp() int64 {
	if m != nil {
		return m.ExpectTimestamp
	}
	return 0
}

type HeyteaTakeaway struct {
	ReceiverTel          string   `protobuf:"bytes,1,opt,name=receiverTel,proto3" json:"receiverTel,omitempty"`
	ReceiverName         string   `protobuf:"bytes,2,opt,name=receiverName,proto3" json:"receiverName,omitempty"`
	ReceiverRegion       string   `protobuf:"bytes,3,opt,name=receiverRegion,proto3" json:"receiverRegion,omitempty"`
	ReceiverAddress      string   `protobuf:"bytes,4,opt,name=receiverAddress,proto3" json:"receiverAddress,omitempty"`
	ReveiverPosition     string   `protobuf:"bytes,5,opt,name=reveiverPosition,proto3" json:"reveiverPosition,omitempty"`
	WxName               string   `protobuf:"bytes,6,opt,name=wxName,proto3" json:"wxName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaTakeaway) Reset()         { *m = HeyteaTakeaway{} }
func (m *HeyteaTakeaway) String() string { return proto.CompactTextString(m) }
func (*HeyteaTakeaway) ProtoMessage()    {}
func (*HeyteaTakeaway) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{2}
}

func (m *HeyteaTakeaway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaTakeaway.Unmarshal(m, b)
}
func (m *HeyteaTakeaway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaTakeaway.Marshal(b, m, deterministic)
}
func (m *HeyteaTakeaway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaTakeaway.Merge(m, src)
}
func (m *HeyteaTakeaway) XXX_Size() int {
	return xxx_messageInfo_HeyteaTakeaway.Size(m)
}
func (m *HeyteaTakeaway) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaTakeaway.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaTakeaway proto.InternalMessageInfo

func (m *HeyteaTakeaway) GetReceiverTel() string {
	if m != nil {
		return m.ReceiverTel
	}
	return ""
}

func (m *HeyteaTakeaway) GetReceiverName() string {
	if m != nil {
		return m.ReceiverName
	}
	return ""
}

func (m *HeyteaTakeaway) GetReceiverRegion() string {
	if m != nil {
		return m.ReceiverRegion
	}
	return ""
}

func (m *HeyteaTakeaway) GetReceiverAddress() string {
	if m != nil {
		return m.ReceiverAddress
	}
	return ""
}

func (m *HeyteaTakeaway) GetReveiverPosition() string {
	if m != nil {
		return m.ReveiverPosition
	}
	return ""
}

func (m *HeyteaTakeaway) GetWxName() string {
	if m != nil {
		return m.WxName
	}
	return ""
}

type HeyteaProductItem struct {
	SkuId                string               `protobuf:"bytes,1,opt,name=skuId,proto3" json:"skuId,omitempty"`
	SkuName              string               `protobuf:"bytes,2,opt,name=skuName,proto3" json:"skuName,omitempty"`
	SalePrice            string               `protobuf:"bytes,3,opt,name=salePrice,proto3" json:"salePrice,omitempty"`
	Qty                  int32                `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	SaleAmount           float64              `protobuf:"fixed64,5,opt,name=saleAmount,proto3" json:"saleAmount,omitempty"`
	ExtraAmount          float64              `protobuf:"fixed64,6,opt,name=extraAmount,proto3" json:"extraAmount,omitempty"`
	ItemAmount           float64              `protobuf:"fixed64,7,opt,name=itemAmount,proto3" json:"itemAmount,omitempty"`
	Memo                 string               `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	Mixs                 []*HeyteaMix         `protobuf:"bytes,9,rep,name=mixs,proto3" json:"mixs,omitempty"`
	Features             []*HeyteaFeature     `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	Combos               []*HeyteaProductItem `protobuf:"bytes,11,rep,name=combos,proto3" json:"combos,omitempty"`
	SeqOrder             int32                `protobuf:"varint,12,opt,name=seqOrder,proto3" json:"seqOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HeyteaProductItem) Reset()         { *m = HeyteaProductItem{} }
func (m *HeyteaProductItem) String() string { return proto.CompactTextString(m) }
func (*HeyteaProductItem) ProtoMessage()    {}
func (*HeyteaProductItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{3}
}

func (m *HeyteaProductItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaProductItem.Unmarshal(m, b)
}
func (m *HeyteaProductItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaProductItem.Marshal(b, m, deterministic)
}
func (m *HeyteaProductItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaProductItem.Merge(m, src)
}
func (m *HeyteaProductItem) XXX_Size() int {
	return xxx_messageInfo_HeyteaProductItem.Size(m)
}
func (m *HeyteaProductItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaProductItem.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaProductItem proto.InternalMessageInfo

func (m *HeyteaProductItem) GetSkuId() string {
	if m != nil {
		return m.SkuId
	}
	return ""
}

func (m *HeyteaProductItem) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *HeyteaProductItem) GetSalePrice() string {
	if m != nil {
		return m.SalePrice
	}
	return ""
}

func (m *HeyteaProductItem) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *HeyteaProductItem) GetSaleAmount() float64 {
	if m != nil {
		return m.SaleAmount
	}
	return 0
}

func (m *HeyteaProductItem) GetExtraAmount() float64 {
	if m != nil {
		return m.ExtraAmount
	}
	return 0
}

func (m *HeyteaProductItem) GetItemAmount() float64 {
	if m != nil {
		return m.ItemAmount
	}
	return 0
}

func (m *HeyteaProductItem) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *HeyteaProductItem) GetMixs() []*HeyteaMix {
	if m != nil {
		return m.Mixs
	}
	return nil
}

func (m *HeyteaProductItem) GetFeatures() []*HeyteaFeature {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *HeyteaProductItem) GetCombos() []*HeyteaProductItem {
	if m != nil {
		return m.Combos
	}
	return nil
}

func (m *HeyteaProductItem) GetSeqOrder() int32 {
	if m != nil {
		return m.SeqOrder
	}
	return 0
}

type HeyteaMix struct {
	MixId                string   `protobuf:"bytes,1,opt,name=mixId,proto3" json:"mixId,omitempty"`
	MixName              string   `protobuf:"bytes,2,opt,name=mixName,proto3" json:"mixName,omitempty"`
	MixPrice             float64  `protobuf:"fixed64,3,opt,name=mixPrice,proto3" json:"mixPrice,omitempty"`
	MixQty               int32    `protobuf:"varint,4,opt,name=mixQty,proto3" json:"mixQty,omitempty"`
	MixAmount            float64  `protobuf:"fixed64,5,opt,name=mixAmount,proto3" json:"mixAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaMix) Reset()         { *m = HeyteaMix{} }
func (m *HeyteaMix) String() string { return proto.CompactTextString(m) }
func (*HeyteaMix) ProtoMessage()    {}
func (*HeyteaMix) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{4}
}

func (m *HeyteaMix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaMix.Unmarshal(m, b)
}
func (m *HeyteaMix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaMix.Marshal(b, m, deterministic)
}
func (m *HeyteaMix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaMix.Merge(m, src)
}
func (m *HeyteaMix) XXX_Size() int {
	return xxx_messageInfo_HeyteaMix.Size(m)
}
func (m *HeyteaMix) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaMix.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaMix proto.InternalMessageInfo

func (m *HeyteaMix) GetMixId() string {
	if m != nil {
		return m.MixId
	}
	return ""
}

func (m *HeyteaMix) GetMixName() string {
	if m != nil {
		return m.MixName
	}
	return ""
}

func (m *HeyteaMix) GetMixPrice() float64 {
	if m != nil {
		return m.MixPrice
	}
	return 0
}

func (m *HeyteaMix) GetMixQty() int32 {
	if m != nil {
		return m.MixQty
	}
	return 0
}

func (m *HeyteaMix) GetMixAmount() float64 {
	if m != nil {
		return m.MixAmount
	}
	return 0
}

type HeyteaFeature struct {
	FeatureId            string   `protobuf:"bytes,1,opt,name=featureId,proto3" json:"featureId,omitempty"`
	FeatureName          string   `protobuf:"bytes,2,opt,name=featureName,proto3" json:"featureName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaFeature) Reset()         { *m = HeyteaFeature{} }
func (m *HeyteaFeature) String() string { return proto.CompactTextString(m) }
func (*HeyteaFeature) ProtoMessage()    {}
func (*HeyteaFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{5}
}

func (m *HeyteaFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaFeature.Unmarshal(m, b)
}
func (m *HeyteaFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaFeature.Marshal(b, m, deterministic)
}
func (m *HeyteaFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaFeature.Merge(m, src)
}
func (m *HeyteaFeature) XXX_Size() int {
	return xxx_messageInfo_HeyteaFeature.Size(m)
}
func (m *HeyteaFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaFeature.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaFeature proto.InternalMessageInfo

func (m *HeyteaFeature) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *HeyteaFeature) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

type HeyteaFee struct {
	FeeType              string   `protobuf:"bytes,1,opt,name=feeType,proto3" json:"feeType,omitempty"`
	FeeName              string   `protobuf:"bytes,2,opt,name=feeName,proto3" json:"feeName,omitempty"`
	FeePrice             string   `protobuf:"bytes,3,opt,name=feePrice,proto3" json:"feePrice,omitempty"`
	FeeQty               int32    `protobuf:"varint,4,opt,name=feeQty,proto3" json:"feeQty,omitempty"`
	FeeAmount            float64  `protobuf:"fixed64,5,opt,name=feeAmount,proto3" json:"feeAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaFee) Reset()         { *m = HeyteaFee{} }
func (m *HeyteaFee) String() string { return proto.CompactTextString(m) }
func (*HeyteaFee) ProtoMessage()    {}
func (*HeyteaFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{6}
}

func (m *HeyteaFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaFee.Unmarshal(m, b)
}
func (m *HeyteaFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaFee.Marshal(b, m, deterministic)
}
func (m *HeyteaFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaFee.Merge(m, src)
}
func (m *HeyteaFee) XXX_Size() int {
	return xxx_messageInfo_HeyteaFee.Size(m)
}
func (m *HeyteaFee) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaFee.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaFee proto.InternalMessageInfo

func (m *HeyteaFee) GetFeeType() string {
	if m != nil {
		return m.FeeType
	}
	return ""
}

func (m *HeyteaFee) GetFeeName() string {
	if m != nil {
		return m.FeeName
	}
	return ""
}

func (m *HeyteaFee) GetFeePrice() string {
	if m != nil {
		return m.FeePrice
	}
	return ""
}

func (m *HeyteaFee) GetFeeQty() int32 {
	if m != nil {
		return m.FeeQty
	}
	return 0
}

func (m *HeyteaFee) GetFeeAmount() float64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

type HeyteaPromotion struct {
	PromoType            string   `protobuf:"bytes,1,opt,name=promoType,proto3" json:"promoType,omitempty"`
	PromoName            string   `protobuf:"bytes,2,opt,name=promoName,proto3" json:"promoName,omitempty"`
	PromoValue           float64  `protobuf:"fixed64,3,opt,name=promoValue,proto3" json:"promoValue,omitempty"`
	PromoAmount          float64  `protobuf:"fixed64,4,opt,name=promoAmount,proto3" json:"promoAmount,omitempty"`
	ReferenceNo          string   `protobuf:"bytes,5,opt,name=referenceNo,proto3" json:"referenceNo,omitempty"`
	CouponType           string   `protobuf:"bytes,6,opt,name=couponType,proto3" json:"couponType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaPromotion) Reset()         { *m = HeyteaPromotion{} }
func (m *HeyteaPromotion) String() string { return proto.CompactTextString(m) }
func (*HeyteaPromotion) ProtoMessage()    {}
func (*HeyteaPromotion) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{7}
}

func (m *HeyteaPromotion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaPromotion.Unmarshal(m, b)
}
func (m *HeyteaPromotion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaPromotion.Marshal(b, m, deterministic)
}
func (m *HeyteaPromotion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaPromotion.Merge(m, src)
}
func (m *HeyteaPromotion) XXX_Size() int {
	return xxx_messageInfo_HeyteaPromotion.Size(m)
}
func (m *HeyteaPromotion) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaPromotion.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaPromotion proto.InternalMessageInfo

func (m *HeyteaPromotion) GetPromoType() string {
	if m != nil {
		return m.PromoType
	}
	return ""
}

func (m *HeyteaPromotion) GetPromoName() string {
	if m != nil {
		return m.PromoName
	}
	return ""
}

func (m *HeyteaPromotion) GetPromoValue() float64 {
	if m != nil {
		return m.PromoValue
	}
	return 0
}

func (m *HeyteaPromotion) GetPromoAmount() float64 {
	if m != nil {
		return m.PromoAmount
	}
	return 0
}

func (m *HeyteaPromotion) GetReferenceNo() string {
	if m != nil {
		return m.ReferenceNo
	}
	return ""
}

func (m *HeyteaPromotion) GetCouponType() string {
	if m != nil {
		return m.CouponType
	}
	return ""
}

type HeyteaPaymentItem struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeyteaPaymentItem) Reset()         { *m = HeyteaPaymentItem{} }
func (m *HeyteaPaymentItem) String() string { return proto.CompactTextString(m) }
func (*HeyteaPaymentItem) ProtoMessage()    {}
func (*HeyteaPaymentItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f79d0570fa6972, []int{8}
}

func (m *HeyteaPaymentItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeyteaPaymentItem.Unmarshal(m, b)
}
func (m *HeyteaPaymentItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeyteaPaymentItem.Marshal(b, m, deterministic)
}
func (m *HeyteaPaymentItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeyteaPaymentItem.Merge(m, src)
}
func (m *HeyteaPaymentItem) XXX_Size() int {
	return xxx_messageInfo_HeyteaPaymentItem.Size(m)
}
func (m *HeyteaPaymentItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HeyteaPaymentItem.DiscardUnknown(m)
}

var xxx_messageInfo_HeyteaPaymentItem proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HeyteaTakeout)(nil), "oms.HeyteaTakeout")
	proto.RegisterType((*HeyteaTakeoutData)(nil), "oms.HeyteaTakeoutData")
	proto.RegisterType((*HeyteaTakeaway)(nil), "oms.HeyteaTakeaway")
	proto.RegisterType((*HeyteaProductItem)(nil), "oms.HeyteaProductItem")
	proto.RegisterType((*HeyteaMix)(nil), "oms.HeyteaMix")
	proto.RegisterType((*HeyteaFeature)(nil), "oms.HeyteaFeature")
	proto.RegisterType((*HeyteaFee)(nil), "oms.HeyteaFee")
	proto.RegisterType((*HeyteaPromotion)(nil), "oms.HeyteaPromotion")
	proto.RegisterType((*HeyteaPaymentItem)(nil), "oms.HeyteaPaymentItem")
}

func init() { proto.RegisterFile("proto/oms/takeout.proto", fileDescriptor_85f79d0570fa6972) }

var fileDescriptor_85f79d0570fa6972 = []byte{
	// 897 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdd, 0x6e, 0x2b, 0x35,
	0x10, 0x56, 0x48, 0x9a, 0x26, 0xee, 0xe9, 0x9f, 0x5b, 0x7a, 0x2c, 0x84, 0x50, 0xb4, 0x42, 0xa8,
	0x3a, 0xaa, 0x52, 0x04, 0x4f, 0x70, 0x24, 0x74, 0x44, 0x25, 0x68, 0xc3, 0x52, 0x71, 0xef, 0xb3,
	0x3b, 0x81, 0x55, 0xe2, 0xf5, 0xd6, 0xf6, 0x9e, 0x6e, 0xae, 0xb8, 0xe6, 0x82, 0x0b, 0xde, 0x83,
	0x97, 0xe1, 0x3d, 0x78, 0x08, 0x34, 0x63, 0xef, 0xae, 0x37, 0x45, 0xe7, 0xae, 0xdf, 0x37, 0x5f,
	0xec, 0x19, 0xcf, 0x37, 0xb3, 0x65, 0xaf, 0x2b, 0xa3, 0x9d, 0xbe, 0xd5, 0xca, 0xde, 0x3a, 0xb9,
	0x01, 0x5d, 0xbb, 0x25, 0x31, 0x7c, 0xac, 0x95, 0x4d, 0x7e, 0x67, 0xc7, 0xdf, 0xc3, 0xce, 0x81,
	0x7c, 0xf4, 0x31, 0xbe, 0x60, 0x47, 0x99, 0x56, 0x95, 0x2c, 0x77, 0xab, 0xba, 0xc8, 0xc5, 0x68,
	0x31, 0xba, 0x9e, 0xa7, 0x31, 0xe5, 0x15, 0xa5, 0xad, 0x15, 0x98, 0x0d, 0xec, 0xc4, 0x27, 0xad,
	0xa2, 0xa3, 0xf8, 0x1b, 0x36, 0xc9, 0xa5, 0x93, 0x62, 0xbc, 0x18, 0x5d, 0x1f, 0x7d, 0x73, 0xb5,
	0xd4, 0xca, 0x2e, 0x07, 0xb7, 0x7c, 0x27, 0x9d, 0x4c, 0x49, 0x93, 0xfc, 0x3d, 0x65, 0xe7, 0x2f,
	0x62, 0xfc, 0x33, 0x36, 0xd3, 0x26, 0x07, 0x63, 0xef, 0x75, 0x48, 0xa1, 0xc3, 0xfc, 0x8a, 0x4d,
	0xed, 0x6f, 0xba, 0xba, 0xcb, 0xc3, 0xd5, 0x01, 0xf1, 0xcf, 0xd9, 0xdc, 0x6b, 0x7e, 0x86, 0x27,
	0xba, 0x7a, 0x9e, 0xf6, 0x04, 0xff, 0x82, 0x31, 0x0f, 0x1e, 0x0b, 0x05, 0x62, 0x42, 0xe1, 0x88,
	0xe1, 0x09, 0x7b, 0x15, 0xc4, 0x4e, 0xba, 0xda, 0x8a, 0x03, 0x52, 0x0c, 0x38, 0x3c, 0x03, 0x9a,
	0x0a, 0x32, 0x47, 0x67, 0x4c, 0xfd, 0x19, 0x3d, 0xc3, 0x05, 0x3b, 0xac, 0xb4, 0x7d, 0xc0, 0x77,
	0x3b, 0xa4, 0x60, 0x0b, 0xf1, 0xcd, 0x72, 0xd8, 0x16, 0x1f, 0xc0, 0x3c, 0xee, 0x2a, 0x10, 0x33,
	0xff, 0x66, 0x11, 0x85, 0x0a, 0xa7, 0x9d, 0xdc, 0xbe, 0x55, 0xba, 0x2e, 0x9d, 0x98, 0x7b, 0x45,
	0x44, 0xe1, 0xed, 0x95, 0x2c, 0xf2, 0x90, 0x1f, 0xf3, 0xb7, 0xf7, 0x4c, 0x1b, 0x0f, 0x07, 0x1c,
	0xf5, 0xf1, 0xf0, 0xfb, 0x2f, 0xd9, 0x71, 0x56, 0x5b, 0xa7, 0x15, 0x98, 0x14, 0xd6, 0xf7, 0x5a,
	0x1c, 0x93, 0x64, 0x48, 0xa2, 0x8a, 0x6a, 0xfe, 0xa1, 0x28, 0x37, 0x94, 0xeb, 0x89, 0x57, 0x0d,
	0x48, 0x7e, 0xc3, 0xce, 0x2b, 0x69, 0x5c, 0x09, 0x66, 0xb5, 0x95, 0x6e, 0xad, 0x8d, 0xba, 0xcb,
	0xc5, 0x29, 0x29, 0x5f, 0x06, 0xf8, 0xd7, 0xec, 0x62, 0x8f, 0xbc, 0x97, 0x0a, 0xc4, 0x19, 0xe9,
	0xff, 0x2f, 0xc4, 0x39, 0x9b, 0x28, 0x50, 0x5a, 0x9c, 0x93, 0x84, 0xfe, 0xe6, 0xb7, 0x6c, 0x86,
	0x06, 0x96, 0xcf, 0x72, 0x27, 0x38, 0x39, 0xeb, 0x62, 0xcf, 0x59, 0x18, 0x4a, 0x3b, 0x11, 0xbf,
	0x61, 0x07, 0x85, 0x03, 0x65, 0xc5, 0xc5, 0x62, 0xbc, 0xe7, 0xc3, 0x95, 0xd1, 0x79, 0x9d, 0xb9,
	0x3b, 0x07, 0x2a, 0xf5, 0x22, 0x9e, 0xb0, 0xc9, 0x1a, 0xc0, 0x8a, 0x4b, 0x12, 0x9f, 0x44, 0xe2,
	0x77, 0x00, 0x29, 0xc5, 0xf8, 0x0d, 0x9b, 0x56, 0x46, 0x2b, 0x6d, 0xc5, 0xa7, 0xa4, 0xba, 0x1c,
	0x1e, 0xa9, 0xb4, 0x2b, 0x74, 0x99, 0x06, 0x0d, 0xbf, 0x66, 0xa7, 0xbd, 0xc1, 0xac, 0x93, 0xaa,
	0x12, 0x57, 0x8b, 0xd1, 0xf5, 0x38, 0xdd, 0xa7, 0x51, 0xd9, 0xdb, 0xc8, 0x2b, 0x5f, 0x7b, 0xe5,
	0x1e, 0x9d, 0xfc, 0x3b, 0x62, 0x27, 0xc3, 0x82, 0xd1, 0x39, 0x06, 0x32, 0x20, 0x27, 0xc1, 0xb6,
	0x9d, 0xd8, 0x88, 0x42, 0x6f, 0xb7, 0x90, 0x1e, 0xde, 0xcf, 0xcd, 0x80, 0xe3, 0x5f, 0xb1, 0x93,
	0x16, 0xa7, 0xf0, 0x6b, 0xa1, 0xcb, 0x30, 0x42, 0x7b, 0x2c, 0xa6, 0xda, 0x32, 0x6f, 0xf3, 0xdc,
	0x80, 0xb5, 0x61, 0x98, 0xf6, 0x69, 0xfe, 0x86, 0x9d, 0x19, 0xf8, 0x40, 0xd4, 0x4a, 0xdb, 0x02,
	0x9f, 0x26, 0x4c, 0xd5, 0x0b, 0x1e, 0x67, 0xfa, 0xb9, 0xa1, 0xdc, 0xfc, 0x54, 0x05, 0x94, 0xfc,
	0x31, 0x6e, 0xb7, 0x43, 0xd4, 0x31, 0x7e, 0xc9, 0x0e, 0xec, 0xa6, 0xbe, 0x6b, 0xb7, 0x93, 0x07,
	0x38, 0x7d, 0x76, 0x53, 0x47, 0x05, 0xb6, 0x10, 0x37, 0x83, 0x95, 0x5b, 0x58, 0x99, 0x22, 0x83,
	0x76, 0x33, 0x74, 0x04, 0x3f, 0x63, 0xe3, 0x27, 0xb7, 0xa3, 0x2a, 0x0e, 0x52, 0xfc, 0x13, 0x27,
	0x09, 0xc3, 0x61, 0x92, 0x30, 0xe7, 0x51, 0x1a, 0x31, 0xf8, 0xe2, 0xd0, 0x38, 0x23, 0x83, 0x60,
	0x4a, 0x82, 0x98, 0xc2, 0x13, 0xd0, 0x55, 0x41, 0x70, 0xe8, 0x4f, 0xe8, 0x99, 0xce, 0xdf, 0xb3,
	0xc8, 0xdf, 0x09, 0x9b, 0xa8, 0xa2, 0xb1, 0x62, 0xfe, 0xc2, 0x80, 0x3f, 0x16, 0x4d, 0x4a, 0x31,
	0xbe, 0x64, 0xb3, 0x35, 0x48, 0x57, 0x1b, 0xc0, 0x0d, 0x80, 0x3a, 0x3e, 0x30, 0x2a, 0x85, 0xd2,
	0x4e, 0xc3, 0x97, 0x6c, 0x9a, 0x69, 0xf5, 0x5e, 0x5b, 0x71, 0xf4, 0xd1, 0x19, 0x08, 0x2a, 0xdc,
	0xbb, 0x16, 0x9e, 0x1e, 0xd0, 0x9e, 0xe2, 0x15, 0x3d, 0x48, 0x87, 0x93, 0x3f, 0x47, 0x6c, 0xde,
	0xe5, 0x83, 0x3d, 0x50, 0x45, 0xd3, 0xf7, 0x80, 0x00, 0xf6, 0x40, 0x15, 0x4d, 0xdc, 0x83, 0x00,
	0xf1, 0x64, 0x55, 0x34, 0x7d, 0x0b, 0x46, 0x69, 0x87, 0xb1, 0xfb, 0xaa, 0x68, 0x7e, 0xea, 0x9a,
	0x10, 0x10, 0xf6, 0x4d, 0x15, 0xcd, 0xa0, 0x0d, 0x3d, 0x91, 0x3c, 0xb4, 0x9f, 0xae, 0x50, 0x36,
	0xca, 0x43, 0xe1, 0x5d, 0x5a, 0x3d, 0x81, 0x4d, 0x0b, 0x20, 0x4a, 0x2f, 0xa6, 0x92, 0xbf, 0xba,
	0x02, 0xdf, 0x01, 0x2d, 0xf3, 0x35, 0x00, 0xad, 0x40, 0x7f, 0x56, 0x0b, 0x43, 0x24, 0x2e, 0x32,
	0x40, 0x2c, 0x72, 0x0d, 0x03, 0x9f, 0x75, 0x18, 0x8b, 0x5c, 0x03, 0x44, 0x45, 0x7a, 0xe4, 0xb3,
	0x1e, 0x7a, 0xad, 0x27, 0x92, 0x7f, 0x46, 0xec, 0x74, 0x6f, 0xbf, 0xe0, 0x2f, 0x68, 0xc3, 0x44,
	0xb9, 0xf5, 0x44, 0x17, 0x8d, 0xf2, 0xeb, 0x09, 0xfa, 0x48, 0x20, 0xf8, 0x45, 0x6e, 0xeb, 0xb6,
	0x11, 0x11, 0x83, 0xaf, 0x44, 0x28, 0xe4, 0x33, 0xf1, 0xd6, 0x8e, 0x28, 0xbf, 0x6e, 0xd6, 0x60,
	0xa0, 0xcc, 0xe0, 0x5e, 0x87, 0x89, 0x8e, 0x29, 0xbc, 0x23, 0xd3, 0x75, 0xa5, 0x4b, 0x4a, 0x30,
	0x7c, 0x26, 0x7b, 0x26, 0xb9, 0xe8, 0x66, 0x5a, 0xee, 0x14, 0x94, 0xe4, 0xc0, 0xf7, 0x53, 0xfa,
	0xa7, 0xe4, 0xdb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x5b, 0x57, 0xe1, 0xaf, 0x08, 0x00,
	0x00,
}
