// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/oauth/oauth.proto

package oauth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPosClientRequest struct {
	PartnerId            uint64   `protobuf:"varint,1,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	ScopeId              uint64   `protobuf:"varint,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	TerminalId           uint64   `protobuf:"varint,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPosClientRequest) Reset()         { *m = GetPosClientRequest{} }
func (m *GetPosClientRequest) String() string { return proto.CompactTextString(m) }
func (*GetPosClientRequest) ProtoMessage()    {}
func (*GetPosClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{0}
}

func (m *GetPosClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPosClientRequest.Unmarshal(m, b)
}
func (m *GetPosClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPosClientRequest.Marshal(b, m, deterministic)
}
func (m *GetPosClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPosClientRequest.Merge(m, src)
}
func (m *GetPosClientRequest) XXX_Size() int {
	return xxx_messageInfo_GetPosClientRequest.Size(m)
}
func (m *GetPosClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPosClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPosClientRequest proto.InternalMessageInfo

func (m *GetPosClientRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *GetPosClientRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *GetPosClientRequest) GetTerminalId() uint64 {
	if m != nil {
		return m.TerminalId
	}
	return 0
}

type GetPosClientResponse struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPosClientResponse) Reset()         { *m = GetPosClientResponse{} }
func (m *GetPosClientResponse) String() string { return proto.CompactTextString(m) }
func (*GetPosClientResponse) ProtoMessage()    {}
func (*GetPosClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{1}
}

func (m *GetPosClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPosClientResponse.Unmarshal(m, b)
}
func (m *GetPosClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPosClientResponse.Marshal(b, m, deterministic)
}
func (m *GetPosClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPosClientResponse.Merge(m, src)
}
func (m *GetPosClientResponse) XXX_Size() int {
	return xxx_messageInfo_GetPosClientResponse.Size(m)
}
func (m *GetPosClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPosClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPosClientResponse proto.InternalMessageInfo

func (m *GetPosClientResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetPosClientResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type GetPosTokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPosTokenRequest) Reset()         { *m = GetPosTokenRequest{} }
func (m *GetPosTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetPosTokenRequest) ProtoMessage()    {}
func (*GetPosTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{2}
}

func (m *GetPosTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPosTokenRequest.Unmarshal(m, b)
}
func (m *GetPosTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPosTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetPosTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPosTokenRequest.Merge(m, src)
}
func (m *GetPosTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetPosTokenRequest.Size(m)
}
func (m *GetPosTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPosTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPosTokenRequest proto.InternalMessageInfo

func (m *GetPosTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetPosTokenRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type GetPosTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn            uint64   `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPosTokenResponse) Reset()         { *m = GetPosTokenResponse{} }
func (m *GetPosTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetPosTokenResponse) ProtoMessage()    {}
func (*GetPosTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{3}
}

func (m *GetPosTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPosTokenResponse.Unmarshal(m, b)
}
func (m *GetPosTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPosTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetPosTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPosTokenResponse.Merge(m, src)
}
func (m *GetPosTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetPosTokenResponse.Size(m)
}
func (m *GetPosTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPosTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPosTokenResponse proto.InternalMessageInfo

func (m *GetPosTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetPosTokenResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *GetPosTokenResponse) GetExpiresIn() uint64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetPosTokenResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type ListUserPermissionRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PartnerId            uint64   `protobuf:"varint,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserPermissionRequest) Reset()         { *m = ListUserPermissionRequest{} }
func (m *ListUserPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserPermissionRequest) ProtoMessage()    {}
func (*ListUserPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{4}
}

func (m *ListUserPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserPermissionRequest.Unmarshal(m, b)
}
func (m *ListUserPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserPermissionRequest.Marshal(b, m, deterministic)
}
func (m *ListUserPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserPermissionRequest.Merge(m, src)
}
func (m *ListUserPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserPermissionRequest.Size(m)
}
func (m *ListUserPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserPermissionRequest proto.InternalMessageInfo

func (m *ListUserPermissionRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListUserPermissionRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

type ListUserPermissionResponse struct {
	PermissionCodes      []string `protobuf:"bytes,1,rep,name=permission_codes,json=permissionCodes,proto3" json:"permission_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserPermissionResponse) Reset()         { *m = ListUserPermissionResponse{} }
func (m *ListUserPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserPermissionResponse) ProtoMessage()    {}
func (*ListUserPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{5}
}

func (m *ListUserPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserPermissionResponse.Unmarshal(m, b)
}
func (m *ListUserPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserPermissionResponse.Marshal(b, m, deterministic)
}
func (m *ListUserPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserPermissionResponse.Merge(m, src)
}
func (m *ListUserPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserPermissionResponse.Size(m)
}
func (m *ListUserPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserPermissionResponse proto.InternalMessageInfo

func (m *ListUserPermissionResponse) GetPermissionCodes() []string {
	if m != nil {
		return m.PermissionCodes
	}
	return nil
}

type IntrospectTokenRequest struct {
	Token                  string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ApiCode                string   `protobuf:"bytes,2,opt,name=api_code,json=apiCode,proto3" json:"api_code,omitempty"`
	Url                    string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	DisablePermissionCheck string   `protobuf:"bytes,4,opt,name=disable_permission_check,json=disablePermissionCheck,proto3" json:"disable_permission_check,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *IntrospectTokenRequest) Reset()         { *m = IntrospectTokenRequest{} }
func (m *IntrospectTokenRequest) String() string { return proto.CompactTextString(m) }
func (*IntrospectTokenRequest) ProtoMessage()    {}
func (*IntrospectTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{6}
}

func (m *IntrospectTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectTokenRequest.Unmarshal(m, b)
}
func (m *IntrospectTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectTokenRequest.Marshal(b, m, deterministic)
}
func (m *IntrospectTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectTokenRequest.Merge(m, src)
}
func (m *IntrospectTokenRequest) XXX_Size() int {
	return xxx_messageInfo_IntrospectTokenRequest.Size(m)
}
func (m *IntrospectTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectTokenRequest proto.InternalMessageInfo

func (m *IntrospectTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IntrospectTokenRequest) GetApiCode() string {
	if m != nil {
		return m.ApiCode
	}
	return ""
}

func (m *IntrospectTokenRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IntrospectTokenRequest) GetDisablePermissionCheck() string {
	if m != nil {
		return m.DisablePermissionCheck
	}
	return ""
}

type IntrospectTokenResponse struct {
	PartnerId            uint64   `protobuf:"varint,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScopeId              uint64   `protobuf:"varint,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	TerminalId           uint64   `protobuf:"varint,5,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntrospectTokenResponse) Reset()         { *m = IntrospectTokenResponse{} }
func (m *IntrospectTokenResponse) String() string { return proto.CompactTextString(m) }
func (*IntrospectTokenResponse) ProtoMessage()    {}
func (*IntrospectTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{7}
}

func (m *IntrospectTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntrospectTokenResponse.Unmarshal(m, b)
}
func (m *IntrospectTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntrospectTokenResponse.Marshal(b, m, deterministic)
}
func (m *IntrospectTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntrospectTokenResponse.Merge(m, src)
}
func (m *IntrospectTokenResponse) XXX_Size() int {
	return xxx_messageInfo_IntrospectTokenResponse.Size(m)
}
func (m *IntrospectTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntrospectTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntrospectTokenResponse proto.InternalMessageInfo

func (m *IntrospectTokenResponse) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *IntrospectTokenResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IntrospectTokenResponse) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *IntrospectTokenResponse) GetTerminalId() uint64 {
	if m != nil {
		return m.TerminalId
	}
	return 0
}

type GetUserRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WithRoles            bool     `protobuf:"varint,2,opt,name=with_roles,json=withRoles,proto3" json:"with_roles,omitempty"`
	WithScope            bool     `protobuf:"varint,3,opt,name=with_scope,json=withScope,proto3" json:"with_scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{8}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserRequest) GetWithRoles() bool {
	if m != nil {
		return m.WithRoles
	}
	return false
}

func (m *GetUserRequest) GetWithScope() bool {
	if m != nil {
		return m.WithScope
	}
	return false
}

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PartnerId            uint64   `protobuf:"varint,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	ScopeId              uint64   `protobuf:"varint,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	IsSystem             bool     `protobuf:"varint,7,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	IsLocked             bool     `protobuf:"varint,8,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	Roles                []*Role  `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *User) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsSystem() bool {
	if m != nil {
		return m.IsSystem
	}
	return false
}

func (m *User) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func (m *User) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Role struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PartnerId            uint64   `protobuf:"varint,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{10}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{11}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type Pong struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfe27e33eeec8e22, []int{12}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPosClientRequest)(nil), "oauth.GetPosClientRequest")
	proto.RegisterType((*GetPosClientResponse)(nil), "oauth.GetPosClientResponse")
	proto.RegisterType((*GetPosTokenRequest)(nil), "oauth.GetPosTokenRequest")
	proto.RegisterType((*GetPosTokenResponse)(nil), "oauth.GetPosTokenResponse")
	proto.RegisterType((*ListUserPermissionRequest)(nil), "oauth.ListUserPermissionRequest")
	proto.RegisterType((*ListUserPermissionResponse)(nil), "oauth.ListUserPermissionResponse")
	proto.RegisterType((*IntrospectTokenRequest)(nil), "oauth.IntrospectTokenRequest")
	proto.RegisterType((*IntrospectTokenResponse)(nil), "oauth.IntrospectTokenResponse")
	proto.RegisterType((*GetUserRequest)(nil), "oauth.GetUserRequest")
	proto.RegisterType((*User)(nil), "oauth.User")
	proto.RegisterType((*Role)(nil), "oauth.Role")
	proto.RegisterType((*Null)(nil), "oauth.Null")
	proto.RegisterType((*Pong)(nil), "oauth.Pong")
}

func init() { proto.RegisterFile("proto/oauth/oauth.proto", fileDescriptor_cfe27e33eeec8e22) }

var fileDescriptor_cfe27e33eeec8e22 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0xad, 0x63, 0xe7, 0xc3, 0x37, 0x7d, 0x6d, 0x35, 0x2f, 0xaf, 0x49, 0xdc, 0x57, 0x9a, 0x9a,
	0x4d, 0x61, 0xd1, 0x88, 0x76, 0x83, 0x58, 0x52, 0x89, 0x62, 0xa9, 0x82, 0xc8, 0x29, 0x88, 0x0d,
	0x18, 0xd7, 0x1e, 0xa5, 0xa3, 0x3a, 0x1e, 0xd7, 0x33, 0x81, 0x66, 0xcb, 0x1a, 0x56, 0x88, 0x5f,
	0xc5, 0x92, 0xbf, 0xc0, 0x8e, 0x3f, 0x81, 0xe6, 0xc3, 0xf9, 0x6a, 0x1a, 0x09, 0xb1, 0x89, 0x7c,
	0xcf, 0xb9, 0x39, 0xbe, 0xf7, 0xdc, 0x3b, 0x63, 0x68, 0x66, 0x39, 0xe5, 0xb4, 0x4b, 0xc3, 0x11,
	0xbf, 0x54, 0xbf, 0x87, 0x12, 0x41, 0x65, 0x19, 0x38, 0xff, 0x0f, 0x28, 0x1d, 0x24, 0xb8, 0x1b,
	0x66, 0xa4, 0x1b, 0xa6, 0x29, 0xe5, 0x21, 0x27, 0x34, 0x65, 0x2a, 0xc9, 0xcd, 0xe0, 0xdf, 0x53,
	0xcc, 0x7b, 0x94, 0x9d, 0x24, 0x04, 0xa7, 0xdc, 0xc7, 0xd7, 0x23, 0xcc, 0x38, 0xda, 0x05, 0xc8,
	0xc2, 0x9c, 0xa7, 0x38, 0x0f, 0x48, 0xdc, 0x32, 0x3a, 0xc6, 0x81, 0xe5, 0xdb, 0x1a, 0xf1, 0x62,
	0xd4, 0x86, 0x1a, 0x8b, 0x68, 0x86, 0x05, 0x59, 0x92, 0x64, 0x55, 0xc6, 0x5e, 0x8c, 0xf6, 0xa0,
	0xce, 0x71, 0x3e, 0x24, 0x69, 0x98, 0x08, 0xd6, 0x94, 0x2c, 0x14, 0x90, 0x17, 0xbb, 0x6f, 0xa0,
	0x31, 0xff, 0x46, 0x96, 0xd1, 0x94, 0x61, 0xb4, 0x03, 0x76, 0x24, 0x91, 0xe2, 0x8d, 0xb6, 0x5f,
	0x53, 0x80, 0x17, 0xa3, 0xfb, 0xf0, 0x8f, 0x26, 0x19, 0x8e, 0x72, 0xcc, 0xe5, 0x5b, 0x6d, 0x7f,
	0x5d, 0x81, 0x7d, 0x89, 0xb9, 0xaf, 0x01, 0x29, 0xe5, 0x73, 0x7a, 0x85, 0xd3, 0xa2, 0x95, 0xbf,
	0xd7, 0xfd, 0x6c, 0x14, 0x26, 0x69, 0x61, 0x5d, 0xf1, 0x3e, 0xac, 0x87, 0x51, 0x84, 0x19, 0x0b,
	0xb8, 0xc0, 0xb5, 0x78, 0x5d, 0x61, 0x32, 0x55, 0xf8, 0x28, 0xb9, 0x80, 0x8f, 0x33, 0xac, 0xc5,
	0x6d, 0x89, 0x9c, 0x8f, 0x33, 0x2c, 0x68, 0x7c, 0x93, 0x91, 0x1c, 0xb3, 0x80, 0xa4, 0xda, 0x2b,
	0x5b, 0x23, 0x5e, 0x8a, 0x1a, 0x50, 0x96, 0xb6, 0xb6, 0x2c, 0xf9, 0x47, 0x15, 0xb8, 0x7d, 0x68,
	0x9f, 0x11, 0xc6, 0x5f, 0x31, 0x9c, 0xf7, 0x84, 0xad, 0x8c, 0x11, 0x3a, 0xe9, 0xb6, 0x09, 0xd5,
	0x11, 0x9b, 0x9d, 0x5a, 0x45, 0x84, 0x5e, 0xbc, 0x30, 0xd1, 0xd2, 0xc2, 0x44, 0xdd, 0x53, 0x70,
	0x96, 0x89, 0xea, 0x4e, 0x1f, 0xc0, 0x56, 0x36, 0x41, 0x83, 0x88, 0xc6, 0x98, 0xb5, 0x8c, 0x8e,
	0x79, 0x60, 0xfb, 0x9b, 0x53, 0xfc, 0x44, 0xc0, 0xee, 0x37, 0x03, 0xb6, 0xbd, 0x94, 0xe7, 0x94,
	0x65, 0x38, 0xe2, 0x73, 0x93, 0x68, 0x40, 0x79, 0xd6, 0x28, 0x15, 0x88, 0x5d, 0x0a, 0x33, 0x22,
	0x45, 0xb5, 0x41, 0xd5, 0x30, 0x23, 0x42, 0x0c, 0x6d, 0x81, 0x39, 0xca, 0x13, 0xe9, 0x8b, 0xed,
	0x8b, 0x47, 0xf4, 0x18, 0x5a, 0x31, 0x61, 0xe1, 0x45, 0x82, 0x83, 0xd9, 0x82, 0x2e, 0x71, 0x74,
	0xa5, 0x4d, 0xda, 0xd6, 0xfc, 0xb4, 0x8b, 0x13, 0xc1, 0xba, 0x5f, 0x0c, 0x68, 0xde, 0xaa, 0x4b,
	0xb7, 0xb7, 0xda, 0x9b, 0x59, 0x4f, 0xcd, 0x39, 0x4f, 0x67, 0x8f, 0x81, 0xb5, 0xf2, 0x18, 0x94,
	0x6f, 0x1d, 0x83, 0x77, 0xb0, 0x71, 0x8a, 0xa5, 0xdf, 0x85, 0x3d, 0x1b, 0x50, 0x9a, 0x4c, 0xad,
	0x44, 0xe4, 0xc4, 0x3e, 0x12, 0x7e, 0x19, 0xe4, 0x34, 0xc1, 0x4c, 0x56, 0x55, 0xf3, 0x6d, 0x81,
	0xf8, 0x02, 0x98, 0xd0, 0x6a, 0x43, 0xcc, 0x29, 0xdd, 0x97, 0x5b, 0xf2, 0xcb, 0x00, 0x4b, 0xa8,
	0x2f, 0x93, 0x5d, 0xd5, 0xec, 0x6c, 0x4f, 0xe6, 0x7c, 0x4f, 0x08, 0xac, 0x34, 0x1c, 0x16, 0xdb,
	0x28, 0x9f, 0x05, 0x26, 0x27, 0x57, 0x56, 0x98, 0x78, 0x16, 0x73, 0xc6, 0xc3, 0x90, 0x24, 0xad,
	0x8a, 0x9a, 0xb3, 0x0c, 0xc4, 0x39, 0x24, 0x2c, 0x60, 0x63, 0xc6, 0xf1, 0xb0, 0x55, 0x95, 0xe5,
	0xd6, 0x08, 0xeb, 0xcb, 0x58, 0x93, 0x09, 0x8d, 0xae, 0x70, 0xdc, 0xaa, 0x15, 0xe4, 0x99, 0x8c,
	0xd1, 0x3e, 0x94, 0x95, 0x07, 0x76, 0xc7, 0x3c, 0xa8, 0x1f, 0xd5, 0x0f, 0xd5, 0x2d, 0x27, 0x6c,
	0xf0, 0x15, 0xe3, 0xbe, 0x05, 0x4b, 0x84, 0x7f, 0xda, 0x6c, 0xd1, 0x91, 0xb9, 0xa4, 0x23, 0x6b,
	0xda, 0x91, 0x5b, 0x01, 0xeb, 0xc5, 0x28, 0x49, 0x5c, 0x07, 0xac, 0x1e, 0x4d, 0x07, 0x22, 0x27,
	0xa3, 0xe9, 0x40, 0x2f, 0xb2, 0x7c, 0x3e, 0xfa, 0x6e, 0x42, 0xed, 0x39, 0xbe, 0x79, 0x29, 0x6a,
	0x43, 0x2e, 0x58, 0x3d, 0x92, 0x0e, 0x50, 0x51, 0xab, 0xf8, 0xb7, 0x53, 0x04, 0x42, 0xc2, 0x5d,
	0x43, 0xd7, 0xb0, 0xb9, 0xb0, 0x90, 0x68, 0x57, 0x67, 0x2c, 0x3f, 0x40, 0xce, 0xbd, 0xbb, 0x68,
	0xb5, 0xc7, 0xee, 0xde, 0xa7, 0x1f, 0x3f, 0xbf, 0x96, 0xda, 0x6e, 0xa3, 0xfb, 0xe1, 0x51, 0x57,
	0x9e, 0xae, 0x2e, 0x99, 0xa4, 0x3e, 0x31, 0x1e, 0xa2, 0x63, 0xa8, 0xeb, 0xa5, 0x7b, 0x3a, 0xf6,
	0x62, 0xf4, 0x9f, 0xd6, 0x9b, 0x5f, 0xc4, 0x49, 0x9d, 0x02, 0x73, 0xd7, 0xd0, 0x7b, 0x68, 0xde,
	0xbe, 0x1a, 0xe4, 0x61, 0x47, 0x1d, 0x9d, 0x79, 0xe7, 0x7d, 0xe4, 0xec, 0xaf, 0xc8, 0xd0, 0x55,
	0xaf, 0xa1, 0x67, 0xb2, 0xac, 0xe2, 0x7e, 0x45, 0xed, 0x69, 0x59, 0x0b, 0x97, 0xb9, 0xe3, 0x2c,
	0xa3, 0x26, 0x3a, 0x1e, 0xac, 0xcf, 0x7e, 0x5a, 0xd0, 0x7c, 0xf6, 0xdc, 0x17, 0xce, 0xd9, 0x59,
	0xca, 0x15, 0x52, 0x17, 0x15, 0xf9, 0x79, 0x3c, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x71,
	0xbf, 0x3e, 0x5e, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HexOauthClient is the client API for HexOauth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HexOauthClient interface {
	Ping(ctx context.Context, in *Null, opts ...grpc.CallOption) (*Pong, error)
	IntrospectToken(ctx context.Context, in *IntrospectTokenRequest, opts ...grpc.CallOption) (*IntrospectTokenResponse, error)
	GetUserById(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUserPermissionCodes(ctx context.Context, in *ListUserPermissionRequest, opts ...grpc.CallOption) (*ListUserPermissionResponse, error)
	GetPosToken(ctx context.Context, in *GetPosTokenRequest, opts ...grpc.CallOption) (*GetPosTokenResponse, error)
	GetPosClient(ctx context.Context, in *GetPosClientRequest, opts ...grpc.CallOption) (*GetPosClientResponse, error)
}

type hexOauthClient struct {
	cc *grpc.ClientConn
}

func NewHexOauthClient(cc *grpc.ClientConn) HexOauthClient {
	return &hexOauthClient{cc}
}

func (c *hexOauthClient) Ping(ctx context.Context, in *Null, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexOauthClient) IntrospectToken(ctx context.Context, in *IntrospectTokenRequest, opts ...grpc.CallOption) (*IntrospectTokenResponse, error) {
	out := new(IntrospectTokenResponse)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/IntrospectToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexOauthClient) GetUserById(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexOauthClient) ListUserPermissionCodes(ctx context.Context, in *ListUserPermissionRequest, opts ...grpc.CallOption) (*ListUserPermissionResponse, error) {
	out := new(ListUserPermissionResponse)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/ListUserPermissionCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexOauthClient) GetPosToken(ctx context.Context, in *GetPosTokenRequest, opts ...grpc.CallOption) (*GetPosTokenResponse, error) {
	out := new(GetPosTokenResponse)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/GetPosToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexOauthClient) GetPosClient(ctx context.Context, in *GetPosClientRequest, opts ...grpc.CallOption) (*GetPosClientResponse, error) {
	out := new(GetPosClientResponse)
	err := c.cc.Invoke(ctx, "/oauth.HexOauth/GetPosClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HexOauthServer is the server API for HexOauth service.
type HexOauthServer interface {
	Ping(context.Context, *Null) (*Pong, error)
	IntrospectToken(context.Context, *IntrospectTokenRequest) (*IntrospectTokenResponse, error)
	GetUserById(context.Context, *GetUserRequest) (*User, error)
	ListUserPermissionCodes(context.Context, *ListUserPermissionRequest) (*ListUserPermissionResponse, error)
	GetPosToken(context.Context, *GetPosTokenRequest) (*GetPosTokenResponse, error)
	GetPosClient(context.Context, *GetPosClientRequest) (*GetPosClientResponse, error)
}

func RegisterHexOauthServer(s *grpc.Server, srv HexOauthServer) {
	s.RegisterService(&_HexOauth_serviceDesc, srv)
}

func _HexOauth_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).Ping(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexOauth_IntrospectToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).IntrospectToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/IntrospectToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).IntrospectToken(ctx, req.(*IntrospectTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexOauth_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).GetUserById(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexOauth_ListUserPermissionCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).ListUserPermissionCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/ListUserPermissionCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).ListUserPermissionCodes(ctx, req.(*ListUserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexOauth_GetPosToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPosTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).GetPosToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/GetPosToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).GetPosToken(ctx, req.(*GetPosTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexOauth_GetPosClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPosClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexOauthServer).GetPosClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauth.HexOauth/GetPosClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexOauthServer).GetPosClient(ctx, req.(*GetPosClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HexOauth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oauth.HexOauth",
	HandlerType: (*HexOauthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _HexOauth_Ping_Handler,
		},
		{
			MethodName: "IntrospectToken",
			Handler:    _HexOauth_IntrospectToken_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _HexOauth_GetUserById_Handler,
		},
		{
			MethodName: "ListUserPermissionCodes",
			Handler:    _HexOauth_ListUserPermissionCodes_Handler,
		},
		{
			MethodName: "GetPosToken",
			Handler:    _HexOauth_GetPosToken_Handler,
		},
		{
			MethodName: "GetPosClient",
			Handler:    _HexOauth_GetPosClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oauth/oauth.proto",
}
