// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ui/proto/coupon/coupon.proto

package coupon

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoRequest) Reset()         { *m = DemoRequest{} }
func (m *DemoRequest) String() string { return proto.CompactTextString(m) }
func (*DemoRequest) ProtoMessage()    {}
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{0}
}

func (m *DemoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoRequest.Unmarshal(m, b)
}
func (m *DemoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoRequest.Marshal(b, m, deterministic)
}
func (m *DemoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoRequest.Merge(m, src)
}
func (m *DemoRequest) XXX_Size() int {
	return xxx_messageInfo_DemoRequest.Size(m)
}
func (m *DemoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DemoRequest proto.InternalMessageInfo

func (m *DemoRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DemoResponse struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoResponse) Reset()         { *m = DemoResponse{} }
func (m *DemoResponse) String() string { return proto.CompactTextString(m) }
func (*DemoResponse) ProtoMessage()    {}
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{1}
}

func (m *DemoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoResponse.Unmarshal(m, b)
}
func (m *DemoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoResponse.Marshal(b, m, deterministic)
}
func (m *DemoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResponse.Merge(m, src)
}
func (m *DemoResponse) XXX_Size() int {
	return xxx_messageInfo_DemoResponse.Size(m)
}
func (m *DemoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResponse proto.InternalMessageInfo

func (m *DemoResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type GetMemberRequest struct {
	//  渠道编码，HEYTEAMEMBER(喜茶会员)
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	//  卡号(card_no、member_code、mobile 三选一)
	CardNo string `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	//  会员编码(card_no、member_code、mobile 三选一)
	MemberCode string `protobuf:"bytes,3,opt,name=member_code,json=memberCode,proto3" json:"member_code,omitempty"`
	//  手机号(card_no、member_code、mobile 三选一)
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	//  敏感信息	密码、辅助码、二磁道信息等,格式- password=123&CVN2=213&expiration=2025/10/13
	SecretContent string `protobuf:"bytes,5,opt,name=secret_content,json=secretContent,proto3" json:"secret_content,omitempty"`
	// 门店id
	StoreId uint64 `protobuf:"varint,6,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 门店partner id
	PartnerId uint64 `protobuf:"varint,7,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	// 门店scope id，如果没有就传0
	ScopeId uint64 `protobuf:"varint,8,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// 用户id
	UserId uint64 `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//  附加扩展信息
	Extend string `protobuf:"bytes,10,opt,name=extend,proto3" json:"extend,omitempty"`
	// 订单信息
	OrderContent         *OrderContent `protobuf:"bytes,11,opt,name=order_content,json=orderContent,proto3" json:"order_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMemberRequest) Reset()         { *m = GetMemberRequest{} }
func (m *GetMemberRequest) String() string { return proto.CompactTextString(m) }
func (*GetMemberRequest) ProtoMessage()    {}
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{2}
}

func (m *GetMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberRequest.Unmarshal(m, b)
}
func (m *GetMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberRequest.Marshal(b, m, deterministic)
}
func (m *GetMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberRequest.Merge(m, src)
}
func (m *GetMemberRequest) XXX_Size() int {
	return xxx_messageInfo_GetMemberRequest.Size(m)
}
func (m *GetMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberRequest proto.InternalMessageInfo

func (m *GetMemberRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetMemberRequest) GetCardNo() string {
	if m != nil {
		return m.CardNo
	}
	return ""
}

func (m *GetMemberRequest) GetMemberCode() string {
	if m != nil {
		return m.MemberCode
	}
	return ""
}

func (m *GetMemberRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetMemberRequest) GetSecretContent() string {
	if m != nil {
		return m.SecretContent
	}
	return ""
}

func (m *GetMemberRequest) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *GetMemberRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *GetMemberRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *GetMemberRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMemberRequest) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *GetMemberRequest) GetOrderContent() *OrderContent {
	if m != nil {
		return m.OrderContent
	}
	return nil
}

type GetMemberResponse struct {
	// 渠道编码
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 账户余额
	AccountBalance float64 `protobuf:"fixed64,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	// 历史总积分
	CreditTotal int32 `protobuf:"varint,3,opt,name=credit_total,json=creditTotal,proto3" json:"credit_total,omitempty"`
	// 积分余额
	CreditBalance int32 `protobuf:"varint,4,opt,name=credit_balance,json=creditBalance,proto3" json:"credit_balance,omitempty"`
	// 会员卡号
	CardNo string `protobuf:"bytes,5,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	// 会员ID
	MemberId string `protobuf:"bytes,6,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// 会员编号
	MemberCode string `protobuf:"bytes,7,opt,name=member_code,json=memberCode,proto3" json:"member_code,omitempty"`
	// 会员名字
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// 性别：MALE/FEMALE/NA(未知)
	Gender string `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	// 手机号码
	Mobile string `protobuf:"bytes,11,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 会员状态(TODO枚举类型待定义)
	Status int32 `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	// 会员等级id
	GradeId string `protobuf:"bytes,13,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	// 会员等级名称
	GradeName string `protobuf:"bytes,14,opt,name=grade_name,json=gradeName,proto3" json:"grade_name,omitempty"`
	// 会员授予时间
	GrantDate string `protobuf:"bytes,15,opt,name=grant_date,json=grantDate,proto3" json:"grant_date,omitempty"`
	// 是否员工
	IsEmployee bool `protobuf:"varint,16,opt,name=is_employee,json=isEmployee,proto3" json:"is_employee,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,17,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 可以用于支付的编码，根据不用厂商，可以是card_no或member_code
	Paycode string `protobuf:"bytes,18,opt,name=paycode,proto3" json:"paycode,omitempty"`
	// 根据会员等级id(grade_id)获取的Hex促销id, 多个以逗号","隔开。POS后台的会员等级主档单独维护一个扩展字段用来映射grade_id，字段名称在集成过程中定义
	PromotionId string `protobuf:"bytes,19,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	// 卡券列表
	Coupons []*Coupon `protobuf:"bytes,20,rep,name=coupons,proto3" json:"coupons,omitempty"`
	// 标签提示语
	Greetings            string   `protobuf:"bytes,21,opt,name=greetings,proto3" json:"greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberResponse) Reset()         { *m = GetMemberResponse{} }
func (m *GetMemberResponse) String() string { return proto.CompactTextString(m) }
func (*GetMemberResponse) ProtoMessage()    {}
func (*GetMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{3}
}

func (m *GetMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberResponse.Unmarshal(m, b)
}
func (m *GetMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberResponse.Marshal(b, m, deterministic)
}
func (m *GetMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberResponse.Merge(m, src)
}
func (m *GetMemberResponse) XXX_Size() int {
	return xxx_messageInfo_GetMemberResponse.Size(m)
}
func (m *GetMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberResponse proto.InternalMessageInfo

func (m *GetMemberResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetMemberResponse) GetAccountBalance() float64 {
	if m != nil {
		return m.AccountBalance
	}
	return 0
}

func (m *GetMemberResponse) GetCreditTotal() int32 {
	if m != nil {
		return m.CreditTotal
	}
	return 0
}

func (m *GetMemberResponse) GetCreditBalance() int32 {
	if m != nil {
		return m.CreditBalance
	}
	return 0
}

func (m *GetMemberResponse) GetCardNo() string {
	if m != nil {
		return m.CardNo
	}
	return ""
}

func (m *GetMemberResponse) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetMemberResponse) GetMemberCode() string {
	if m != nil {
		return m.MemberCode
	}
	return ""
}

func (m *GetMemberResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetMemberResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *GetMemberResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetMemberResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetMemberResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetMemberResponse) GetGradeId() string {
	if m != nil {
		return m.GradeId
	}
	return ""
}

func (m *GetMemberResponse) GetGradeName() string {
	if m != nil {
		return m.GradeName
	}
	return ""
}

func (m *GetMemberResponse) GetGrantDate() string {
	if m != nil {
		return m.GrantDate
	}
	return ""
}

func (m *GetMemberResponse) GetIsEmployee() bool {
	if m != nil {
		return m.IsEmployee
	}
	return false
}

func (m *GetMemberResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GetMemberResponse) GetPaycode() string {
	if m != nil {
		return m.Paycode
	}
	return ""
}

func (m *GetMemberResponse) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

func (m *GetMemberResponse) GetCoupons() []*Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func (m *GetMemberResponse) GetGreetings() string {
	if m != nil {
		return m.Greetings
	}
	return ""
}

// 卡券信息
type Coupon struct {
	CodeNo               string   `protobuf:"bytes,1,opt,name=code_no,json=codeNo,proto3" json:"code_no,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Prepay               float64  `protobuf:"fixed64,5,opt,name=prepay,proto3" json:"prepay,omitempty"`
	TypeCode             string   `protobuf:"bytes,6,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	ParValue             float64  `protobuf:"fixed64,7,opt,name=par_value,json=parValue,proto3" json:"par_value,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	StartDate            string   `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	ExpiredDate          string   `protobuf:"bytes,10,opt,name=expired_date,json=expiredDate,proto3" json:"expired_date,omitempty"`
	Status               int32    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	AvailableCount       int32    `protobuf:"varint,12,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	UseType              string   `protobuf:"bytes,13,opt,name=use_type,json=useType,proto3" json:"use_type,omitempty"`
	PromotionId          string   `protobuf:"bytes,14,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	StartTimestamp       string   `protobuf:"bytes,15,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	ExpiredTimestamp     string   `protobuf:"bytes,16,opt,name=expired_timestamp,json=expiredTimestamp,proto3" json:"expired_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coupon) Reset()         { *m = Coupon{} }
func (m *Coupon) String() string { return proto.CompactTextString(m) }
func (*Coupon) ProtoMessage()    {}
func (*Coupon) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{4}
}

func (m *Coupon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coupon.Unmarshal(m, b)
}
func (m *Coupon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coupon.Marshal(b, m, deterministic)
}
func (m *Coupon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coupon.Merge(m, src)
}
func (m *Coupon) XXX_Size() int {
	return xxx_messageInfo_Coupon.Size(m)
}
func (m *Coupon) XXX_DiscardUnknown() {
	xxx_messageInfo_Coupon.DiscardUnknown(m)
}

var xxx_messageInfo_Coupon proto.InternalMessageInfo

func (m *Coupon) GetCodeNo() string {
	if m != nil {
		return m.CodeNo
	}
	return ""
}

func (m *Coupon) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Coupon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Coupon) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Coupon) GetPrepay() float64 {
	if m != nil {
		return m.Prepay
	}
	return 0
}

func (m *Coupon) GetTypeCode() string {
	if m != nil {
		return m.TypeCode
	}
	return ""
}

func (m *Coupon) GetParValue() float64 {
	if m != nil {
		return m.ParValue
	}
	return 0
}

func (m *Coupon) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Coupon) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Coupon) GetExpiredDate() string {
	if m != nil {
		return m.ExpiredDate
	}
	return ""
}

func (m *Coupon) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Coupon) GetAvailableCount() int32 {
	if m != nil {
		return m.AvailableCount
	}
	return 0
}

func (m *Coupon) GetUseType() string {
	if m != nil {
		return m.UseType
	}
	return ""
}

func (m *Coupon) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

func (m *Coupon) GetStartTimestamp() string {
	if m != nil {
		return m.StartTimestamp
	}
	return ""
}

func (m *Coupon) GetExpiredTimestamp() string {
	if m != nil {
		return m.ExpiredTimestamp
	}
	return ""
}

// 卡券请求信息
type CouponReq struct {
	// 券号(用于核销)
	CodeNo string `protobuf:"bytes,1,opt,name=code_no,json=codeNo,proto3" json:"code_no,omitempty"`
	// 券密码
	PasswordCode string `protobuf:"bytes,2,opt,name=password_code,json=passwordCode,proto3" json:"password_code,omitempty"`
	// 核销次数，对应多次券，验证是否可以核销的次数
	Qty                  int32    `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CouponReq) Reset()         { *m = CouponReq{} }
func (m *CouponReq) String() string { return proto.CompactTextString(m) }
func (*CouponReq) ProtoMessage()    {}
func (*CouponReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{5}
}

func (m *CouponReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CouponReq.Unmarshal(m, b)
}
func (m *CouponReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CouponReq.Marshal(b, m, deterministic)
}
func (m *CouponReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CouponReq.Merge(m, src)
}
func (m *CouponReq) XXX_Size() int {
	return xxx_messageInfo_CouponReq.Size(m)
}
func (m *CouponReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CouponReq.DiscardUnknown(m)
}

var xxx_messageInfo_CouponReq proto.InternalMessageInfo

func (m *CouponReq) GetCodeNo() string {
	if m != nil {
		return m.CodeNo
	}
	return ""
}

func (m *CouponReq) GetPasswordCode() string {
	if m != nil {
		return m.PasswordCode
	}
	return ""
}

func (m *CouponReq) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

// 订单信息
type OrderContent struct {
	// 交易订单ticket id
	OrderTicketId string `protobuf:"bytes,1,opt,name=order_ticket_id,json=orderTicketId,proto3" json:"order_ticket_id,omitempty"`
	// pos id
	PosId string `protobuf:"bytes,2,opt,name=pos_id,json=posId,proto3" json:"pos_id,omitempty"`
	// pos编码
	PosCode string `protobuf:"bytes,3,opt,name=pos_code,json=posCode,proto3" json:"pos_code,omitempty"`
	// 桌位号
	TableNo string `protobuf:"bytes,4,opt,name=table_no,json=tableNo,proto3" json:"table_no,omitempty"`
	// 交易时间 "2020-01-08 01:12:40"
	SalesTime string `protobuf:"bytes,5,opt,name=sales_time,json=salesTime,proto3" json:"sales_time,omitempty"`
	// 营业日期 "2020-01-07"
	SalesDate string `protobuf:"bytes,6,opt,name=sales_date,json=salesDate,proto3" json:"sales_date,omitempty"`
	// 毛额
	GrossAmount float64 `protobuf:"fixed64,7,opt,name=gross_amount,json=grossAmount,proto3" json:"gross_amount,omitempty"`
	// 净额
	NetAmount float64 `protobuf:"fixed64,8,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	// 商品列表，部分第三方支付需要根据商品列表进行促销计算
	Products             []*Product `protobuf:"bytes,9,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderContent) Reset()         { *m = OrderContent{} }
func (m *OrderContent) String() string { return proto.CompactTextString(m) }
func (*OrderContent) ProtoMessage()    {}
func (*OrderContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{6}
}

func (m *OrderContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderContent.Unmarshal(m, b)
}
func (m *OrderContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderContent.Marshal(b, m, deterministic)
}
func (m *OrderContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderContent.Merge(m, src)
}
func (m *OrderContent) XXX_Size() int {
	return xxx_messageInfo_OrderContent.Size(m)
}
func (m *OrderContent) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderContent.DiscardUnknown(m)
}

var xxx_messageInfo_OrderContent proto.InternalMessageInfo

func (m *OrderContent) GetOrderTicketId() string {
	if m != nil {
		return m.OrderTicketId
	}
	return ""
}

func (m *OrderContent) GetPosId() string {
	if m != nil {
		return m.PosId
	}
	return ""
}

func (m *OrderContent) GetPosCode() string {
	if m != nil {
		return m.PosCode
	}
	return ""
}

func (m *OrderContent) GetTableNo() string {
	if m != nil {
		return m.TableNo
	}
	return ""
}

func (m *OrderContent) GetSalesTime() string {
	if m != nil {
		return m.SalesTime
	}
	return ""
}

func (m *OrderContent) GetSalesDate() string {
	if m != nil {
		return m.SalesDate
	}
	return ""
}

func (m *OrderContent) GetGrossAmount() float64 {
	if m != nil {
		return m.GrossAmount
	}
	return 0
}

func (m *OrderContent) GetNetAmount() float64 {
	if m != nil {
		return m.NetAmount
	}
	return 0
}

func (m *OrderContent) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

// 会员信息
type MemberContent struct {
	// 卡号(card_no、member_code、mobile 三选一)
	CardNo string `protobuf:"bytes,1,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	// 会员编码(card_no、member_code、mobile 三选一)
	MemberCode string `protobuf:"bytes,2,opt,name=member_code,json=memberCode,proto3" json:"member_code,omitempty"`
	// 手机号(card_no、member_code、mobile 三选一)
	Mobile string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 敏感信息     密码、辅助码、二磁道信息等,格式- password=123&CVN2=213&expiration=2025/10/13
	SecretContent        string   `protobuf:"bytes,4,opt,name=secret_content,json=secretContent,proto3" json:"secret_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberContent) Reset()         { *m = MemberContent{} }
func (m *MemberContent) String() string { return proto.CompactTextString(m) }
func (*MemberContent) ProtoMessage()    {}
func (*MemberContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{7}
}

func (m *MemberContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberContent.Unmarshal(m, b)
}
func (m *MemberContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberContent.Marshal(b, m, deterministic)
}
func (m *MemberContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberContent.Merge(m, src)
}
func (m *MemberContent) XXX_Size() int {
	return xxx_messageInfo_MemberContent.Size(m)
}
func (m *MemberContent) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberContent.DiscardUnknown(m)
}

var xxx_messageInfo_MemberContent proto.InternalMessageInfo

func (m *MemberContent) GetCardNo() string {
	if m != nil {
		return m.CardNo
	}
	return ""
}

func (m *MemberContent) GetMemberCode() string {
	if m != nil {
		return m.MemberCode
	}
	return ""
}

func (m *MemberContent) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberContent) GetSecretContent() string {
	if m != nil {
		return m.SecretContent
	}
	return ""
}

// 商品
type Product struct {
	// 商品id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 商品名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 商品编码
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// 数量
	Qty float64 `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty"`
	// 价格(每个商品的)
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// 加料
	Accessories []*Product `protobuf:"bytes,6,rep,name=accessories,proto3" json:"accessories,omitempty"`
	// 属性
	Attributes           []*Attribute `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{8}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Product) GetQty() float64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetAccessories() []*Product {
	if m != nil {
		return m.Accessories
	}
	return nil
}

func (m *Product) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// 属性
type Attribute struct {
	// 属性名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 属性编码
	NameCode string `protobuf:"bytes,2,opt,name=name_code,json=nameCode,proto3" json:"name_code,omitempty"`
	// 属性值
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// 属性值编码
	ValueCode string `protobuf:"bytes,4,opt,name=value_code,json=valueCode,proto3" json:"value_code,omitempty"`
	// 属性价格
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{9}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetNameCode() string {
	if m != nil {
		return m.NameCode
	}
	return ""
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Attribute) GetValueCode() string {
	if m != nil {
		return m.ValueCode
	}
	return ""
}

func (m *Attribute) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// 【第三方促销计算】请求
type CalculatePromotionRequest struct {
	// 渠道编码，HEYTEAMEMBER(喜茶会员)
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 门店id
	StoreId uint64 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 门店partner id
	PartnerId uint64 `protobuf:"varint,3,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	// 门店scope id，如果没有就传0
	ScopeId uint64 `protobuf:"varint,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// 用户id
	UserId uint64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 订单信息
	OrderContent *OrderContent `protobuf:"bytes,6,opt,name=order_content,json=orderContent,proto3" json:"order_content,omitempty"`
	// 会员信息
	MemberContent *MemberContent `protobuf:"bytes,7,opt,name=member_content,json=memberContent,proto3" json:"member_content,omitempty"`
	// 附加扩展信息
	Extend               string   `protobuf:"bytes,8,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatePromotionRequest) Reset()         { *m = CalculatePromotionRequest{} }
func (m *CalculatePromotionRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatePromotionRequest) ProtoMessage()    {}
func (*CalculatePromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{10}
}

func (m *CalculatePromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatePromotionRequest.Unmarshal(m, b)
}
func (m *CalculatePromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatePromotionRequest.Marshal(b, m, deterministic)
}
func (m *CalculatePromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatePromotionRequest.Merge(m, src)
}
func (m *CalculatePromotionRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatePromotionRequest.Size(m)
}
func (m *CalculatePromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatePromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatePromotionRequest proto.InternalMessageInfo

func (m *CalculatePromotionRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CalculatePromotionRequest) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CalculatePromotionRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *CalculatePromotionRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *CalculatePromotionRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CalculatePromotionRequest) GetOrderContent() *OrderContent {
	if m != nil {
		return m.OrderContent
	}
	return nil
}

func (m *CalculatePromotionRequest) GetMemberContent() *MemberContent {
	if m != nil {
		return m.MemberContent
	}
	return nil
}

func (m *CalculatePromotionRequest) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

// 【第三方促销计算】结果
type CalculatePromotionResponse struct {
	// 渠道编码
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 根据返回的促销信息会员获取的Hex促销id, 多个以逗号","隔开。不包含卡券。
	PromotionId string `protobuf:"bytes,2,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	// 卡券列表
	Coupons              []*Coupon `protobuf:"bytes,3,rep,name=coupons,proto3" json:"coupons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CalculatePromotionResponse) Reset()         { *m = CalculatePromotionResponse{} }
func (m *CalculatePromotionResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatePromotionResponse) ProtoMessage()    {}
func (*CalculatePromotionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{11}
}

func (m *CalculatePromotionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatePromotionResponse.Unmarshal(m, b)
}
func (m *CalculatePromotionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatePromotionResponse.Marshal(b, m, deterministic)
}
func (m *CalculatePromotionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatePromotionResponse.Merge(m, src)
}
func (m *CalculatePromotionResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatePromotionResponse.Size(m)
}
func (m *CalculatePromotionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatePromotionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatePromotionResponse proto.InternalMessageInfo

func (m *CalculatePromotionResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CalculatePromotionResponse) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

func (m *CalculatePromotionResponse) GetCoupons() []*Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

// 【卡券验证】请求
type VerifyCouponsRequest struct {
	// 渠道编码，HEYTEAMEMBER(喜茶会员)
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 会员信息
	MemberContent *MemberContent `protobuf:"bytes,2,opt,name=member_content,json=memberContent,proto3" json:"member_content,omitempty"`
	// 门店id
	StoreId uint64 `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 门店partner id
	PartnerId uint64 `protobuf:"varint,4,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	// 门店scope id，如果没有就传0
	ScopeId uint64 `protobuf:"varint,5,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// 用户id
	UserId uint64 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 卡券列表
	Coupons []*CouponReq `protobuf:"bytes,7,rep,name=coupons,proto3" json:"coupons,omitempty"`
	// 是否返回对应促销/Hex券id等主档，默认false
	IncludeMetadata      bool     `protobuf:"varint,8,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyCouponsRequest) Reset()         { *m = VerifyCouponsRequest{} }
func (m *VerifyCouponsRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyCouponsRequest) ProtoMessage()    {}
func (*VerifyCouponsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{12}
}

func (m *VerifyCouponsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCouponsRequest.Unmarshal(m, b)
}
func (m *VerifyCouponsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCouponsRequest.Marshal(b, m, deterministic)
}
func (m *VerifyCouponsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCouponsRequest.Merge(m, src)
}
func (m *VerifyCouponsRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyCouponsRequest.Size(m)
}
func (m *VerifyCouponsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCouponsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCouponsRequest proto.InternalMessageInfo

func (m *VerifyCouponsRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *VerifyCouponsRequest) GetMemberContent() *MemberContent {
	if m != nil {
		return m.MemberContent
	}
	return nil
}

func (m *VerifyCouponsRequest) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *VerifyCouponsRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *VerifyCouponsRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *VerifyCouponsRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VerifyCouponsRequest) GetCoupons() []*CouponReq {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func (m *VerifyCouponsRequest) GetIncludeMetadata() bool {
	if m != nil {
		return m.IncludeMetadata
	}
	return false
}

// 【卡券验证】结果
type VerifyCouponsResponse struct {
	// 渠道编码
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 是否验证成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 异常编码，查看交易接口异常返回
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 异常信息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 第三方编码
	ResponseCode string `protobuf:"bytes,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// 第三方报文(500字符以内)
	ResponseContent string `protobuf:"bytes,6,opt,name=response_content,json=responseContent,proto3" json:"response_content,omitempty"`
	// 异常信息
	Details              []*Coupon `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VerifyCouponsResponse) Reset()         { *m = VerifyCouponsResponse{} }
func (m *VerifyCouponsResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyCouponsResponse) ProtoMessage()    {}
func (*VerifyCouponsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{13}
}

func (m *VerifyCouponsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCouponsResponse.Unmarshal(m, b)
}
func (m *VerifyCouponsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCouponsResponse.Marshal(b, m, deterministic)
}
func (m *VerifyCouponsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCouponsResponse.Merge(m, src)
}
func (m *VerifyCouponsResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyCouponsResponse.Size(m)
}
func (m *VerifyCouponsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCouponsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCouponsResponse proto.InternalMessageInfo

func (m *VerifyCouponsResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *VerifyCouponsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *VerifyCouponsResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *VerifyCouponsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyCouponsResponse) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *VerifyCouponsResponse) GetResponseContent() string {
	if m != nil {
		return m.ResponseContent
	}
	return ""
}

func (m *VerifyCouponsResponse) GetDetails() []*Coupon {
	if m != nil {
		return m.Details
	}
	return nil
}

// 【卡券核销】请求
type ConsumeCouponsRequest struct {
	// 渠道编码，HEYTEAMEMBER(喜茶会员)
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 支付时传给第三方接口的唯一标识id
	BatchTicketId string `protobuf:"bytes,2,opt,name=batch_ticket_id,json=batchTicketId,proto3" json:"batch_ticket_id,omitempty"`
	// 门店id
	StoreId uint64 `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 门店partner id
	PartnerId uint64 `protobuf:"varint,4,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	// 门店scope id，如果没有就传0
	ScopeId uint64 `protobuf:"varint,5,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// 用户id
	UserId uint64 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 会员信息
	MemberContent *MemberContent `protobuf:"bytes,7,opt,name=member_content,json=memberContent,proto3" json:"member_content,omitempty"`
	// 订单信息
	OrderContent *OrderContent `protobuf:"bytes,8,opt,name=order_content,json=orderContent,proto3" json:"order_content,omitempty"`
	// 订单信息
	Coupons              []*CouponReq `protobuf:"bytes,9,rep,name=coupons,proto3" json:"coupons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConsumeCouponsRequest) Reset()         { *m = ConsumeCouponsRequest{} }
func (m *ConsumeCouponsRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeCouponsRequest) ProtoMessage()    {}
func (*ConsumeCouponsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{14}
}

func (m *ConsumeCouponsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeCouponsRequest.Unmarshal(m, b)
}
func (m *ConsumeCouponsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeCouponsRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeCouponsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeCouponsRequest.Merge(m, src)
}
func (m *ConsumeCouponsRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeCouponsRequest.Size(m)
}
func (m *ConsumeCouponsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeCouponsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeCouponsRequest proto.InternalMessageInfo

func (m *ConsumeCouponsRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ConsumeCouponsRequest) GetBatchTicketId() string {
	if m != nil {
		return m.BatchTicketId
	}
	return ""
}

func (m *ConsumeCouponsRequest) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *ConsumeCouponsRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *ConsumeCouponsRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *ConsumeCouponsRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConsumeCouponsRequest) GetMemberContent() *MemberContent {
	if m != nil {
		return m.MemberContent
	}
	return nil
}

func (m *ConsumeCouponsRequest) GetOrderContent() *OrderContent {
	if m != nil {
		return m.OrderContent
	}
	return nil
}

func (m *ConsumeCouponsRequest) GetCoupons() []*CouponReq {
	if m != nil {
		return m.Coupons
	}
	return nil
}

// 【卡券核销】结果
type ConsumeCouponsResponse struct {
	// 渠道编码
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 是否验证成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 异常编码，查看交易接口的error_code
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 异常信息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 第三方编码
	ResponseCode string `protobuf:"bytes,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// 第三方报文(500字符以内)
	ResponseContent      string   `protobuf:"bytes,6,opt,name=response_content,json=responseContent,proto3" json:"response_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeCouponsResponse) Reset()         { *m = ConsumeCouponsResponse{} }
func (m *ConsumeCouponsResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumeCouponsResponse) ProtoMessage()    {}
func (*ConsumeCouponsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{15}
}

func (m *ConsumeCouponsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeCouponsResponse.Unmarshal(m, b)
}
func (m *ConsumeCouponsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeCouponsResponse.Marshal(b, m, deterministic)
}
func (m *ConsumeCouponsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeCouponsResponse.Merge(m, src)
}
func (m *ConsumeCouponsResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumeCouponsResponse.Size(m)
}
func (m *ConsumeCouponsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeCouponsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeCouponsResponse proto.InternalMessageInfo

func (m *ConsumeCouponsResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ConsumeCouponsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ConsumeCouponsResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *ConsumeCouponsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConsumeCouponsResponse) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *ConsumeCouponsResponse) GetResponseContent() string {
	if m != nil {
		return m.ResponseContent
	}
	return ""
}

// 【卡券反核销】请求
type CancelCouponsRequest struct {
	// 渠道编码，HEYTEAMEMBER(喜茶会员)
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 支付时传给第三方接口的唯一标识id
	BatchTicketId string `protobuf:"bytes,2,opt,name=batch_ticket_id,json=batchTicketId,proto3" json:"batch_ticket_id,omitempty"`
	// 门店id
	StoreId uint64 `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 门店partner id
	PartnerId uint64 `protobuf:"varint,4,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	// 门店scope id，如果没有就传0
	ScopeId uint64 `protobuf:"varint,5,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// 用户id
	UserId uint64 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 会员信息
	MemberContent *MemberContent `protobuf:"bytes,7,opt,name=member_content,json=memberContent,proto3" json:"member_content,omitempty"`
	// 订单信息
	OrderContent *OrderContent `protobuf:"bytes,8,opt,name=order_content,json=orderContent,proto3" json:"order_content,omitempty"`
	// 订单信息
	Coupons              []*CouponReq `protobuf:"bytes,9,rep,name=coupons,proto3" json:"coupons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CancelCouponsRequest) Reset()         { *m = CancelCouponsRequest{} }
func (m *CancelCouponsRequest) String() string { return proto.CompactTextString(m) }
func (*CancelCouponsRequest) ProtoMessage()    {}
func (*CancelCouponsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{16}
}

func (m *CancelCouponsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCouponsRequest.Unmarshal(m, b)
}
func (m *CancelCouponsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCouponsRequest.Marshal(b, m, deterministic)
}
func (m *CancelCouponsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCouponsRequest.Merge(m, src)
}
func (m *CancelCouponsRequest) XXX_Size() int {
	return xxx_messageInfo_CancelCouponsRequest.Size(m)
}
func (m *CancelCouponsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCouponsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCouponsRequest proto.InternalMessageInfo

func (m *CancelCouponsRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CancelCouponsRequest) GetBatchTicketId() string {
	if m != nil {
		return m.BatchTicketId
	}
	return ""
}

func (m *CancelCouponsRequest) GetStoreId() uint64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CancelCouponsRequest) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *CancelCouponsRequest) GetScopeId() uint64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *CancelCouponsRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CancelCouponsRequest) GetMemberContent() *MemberContent {
	if m != nil {
		return m.MemberContent
	}
	return nil
}

func (m *CancelCouponsRequest) GetOrderContent() *OrderContent {
	if m != nil {
		return m.OrderContent
	}
	return nil
}

func (m *CancelCouponsRequest) GetCoupons() []*CouponReq {
	if m != nil {
		return m.Coupons
	}
	return nil
}

// 【卡券反核销】结果
type CancelCouponsResponse struct {
	// 渠道编码
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// 是否验证成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 异常编码，查看交易接口的error_code
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 异常信息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 第三方编码
	ResponseCode string `protobuf:"bytes,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// 第三方报文(500字符以内)
	ResponseContent      string   `protobuf:"bytes,6,opt,name=response_content,json=responseContent,proto3" json:"response_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelCouponsResponse) Reset()         { *m = CancelCouponsResponse{} }
func (m *CancelCouponsResponse) String() string { return proto.CompactTextString(m) }
func (*CancelCouponsResponse) ProtoMessage()    {}
func (*CancelCouponsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36ce65345d1c7a0b, []int{17}
}

func (m *CancelCouponsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCouponsResponse.Unmarshal(m, b)
}
func (m *CancelCouponsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCouponsResponse.Marshal(b, m, deterministic)
}
func (m *CancelCouponsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCouponsResponse.Merge(m, src)
}
func (m *CancelCouponsResponse) XXX_Size() int {
	return xxx_messageInfo_CancelCouponsResponse.Size(m)
}
func (m *CancelCouponsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCouponsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCouponsResponse proto.InternalMessageInfo

func (m *CancelCouponsResponse) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CancelCouponsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CancelCouponsResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *CancelCouponsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CancelCouponsResponse) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *CancelCouponsResponse) GetResponseContent() string {
	if m != nil {
		return m.ResponseContent
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoRequest)(nil), "coupon.DemoRequest")
	proto.RegisterType((*DemoResponse)(nil), "coupon.DemoResponse")
	proto.RegisterType((*GetMemberRequest)(nil), "coupon.GetMemberRequest")
	proto.RegisterType((*GetMemberResponse)(nil), "coupon.GetMemberResponse")
	proto.RegisterType((*Coupon)(nil), "coupon.Coupon")
	proto.RegisterType((*CouponReq)(nil), "coupon.CouponReq")
	proto.RegisterType((*OrderContent)(nil), "coupon.OrderContent")
	proto.RegisterType((*MemberContent)(nil), "coupon.MemberContent")
	proto.RegisterType((*Product)(nil), "coupon.Product")
	proto.RegisterType((*Attribute)(nil), "coupon.Attribute")
	proto.RegisterType((*CalculatePromotionRequest)(nil), "coupon.CalculatePromotionRequest")
	proto.RegisterType((*CalculatePromotionResponse)(nil), "coupon.CalculatePromotionResponse")
	proto.RegisterType((*VerifyCouponsRequest)(nil), "coupon.VerifyCouponsRequest")
	proto.RegisterType((*VerifyCouponsResponse)(nil), "coupon.VerifyCouponsResponse")
	proto.RegisterType((*ConsumeCouponsRequest)(nil), "coupon.ConsumeCouponsRequest")
	proto.RegisterType((*ConsumeCouponsResponse)(nil), "coupon.ConsumeCouponsResponse")
	proto.RegisterType((*CancelCouponsRequest)(nil), "coupon.CancelCouponsRequest")
	proto.RegisterType((*CancelCouponsResponse)(nil), "coupon.CancelCouponsResponse")
}

func init() { proto.RegisterFile("ui/proto/coupon/coupon.proto", fileDescriptor_36ce65345d1c7a0b) }

var fileDescriptor_36ce65345d1c7a0b = []byte{
	// 1665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x6f, 0xdd, 0x44,
	0x17, 0x96, 0xef, 0xb7, 0xcf, 0xfd, 0x4a, 0xa6, 0x49, 0x5f, 0x27, 0x4d, 0xdf, 0x37, 0xf1, 0xab,
	0xb6, 0x69, 0x83, 0x1a, 0x1a, 0x56, 0x54, 0x6c, 0x4a, 0x8a, 0x50, 0x16, 0x09, 0x95, 0x89, 0xba,
	0x61, 0x71, 0x35, 0xb1, 0x87, 0x5b, 0x83, 0xed, 0x71, 0x3d, 0xe3, 0xd0, 0x2c, 0x90, 0x10, 0x2c,
	0x60, 0xc3, 0x8a, 0x3f, 0xc2, 0x82, 0xff, 0xc1, 0x82, 0x8f, 0x5f, 0x80, 0x58, 0x20, 0xf8, 0x0b,
	0x08, 0xcd, 0x99, 0xf1, 0xbd, 0xbe, 0x9f, 0x09, 0x42, 0xea, 0xa2, 0x62, 0x75, 0x7d, 0x9e, 0x73,
	0xc6, 0x33, 0xe7, 0x3c, 0xcf, 0x99, 0x99, 0x6b, 0xd8, 0xca, 0xc3, 0xfd, 0x34, 0xe3, 0x92, 0xef,
	0xfb, 0x3c, 0x4f, 0x79, 0x62, 0x7e, 0xee, 0x23, 0x46, 0x1a, 0xda, 0xda, 0xdc, 0x1a, 0x72, 0x3e,
	0x8c, 0xd8, 0x3e, 0x4d, 0xc3, 0x7d, 0x9a, 0x24, 0x5c, 0x52, 0x19, 0xf2, 0x44, 0xe8, 0x28, 0x77,
	0x07, 0xda, 0x8f, 0x59, 0xcc, 0x3d, 0xf6, 0x3c, 0x67, 0x42, 0x12, 0x02, 0xb5, 0x80, 0x4a, 0xea,
	0x58, 0xdb, 0xd6, 0xae, 0xed, 0xe1, 0xb3, 0xeb, 0x42, 0x47, 0x87, 0x88, 0x94, 0x27, 0x82, 0xa9,
	0x98, 0x8f, 0x04, 0x4f, 0x8a, 0x18, 0xf5, 0xec, 0xfe, 0x5a, 0x81, 0x95, 0x77, 0x99, 0x3c, 0x66,
	0xf1, 0x19, 0xcb, 0x8a, 0x97, 0x39, 0xd0, 0xf4, 0x9f, 0xd1, 0x24, 0x61, 0x91, 0x89, 0x2d, 0x4c,
	0xf2, 0x1f, 0x68, 0xfa, 0x34, 0x0b, 0x06, 0x09, 0x77, 0x2a, 0xe8, 0x69, 0x28, 0xf3, 0x84, 0x93,
	0xff, 0x41, 0x3b, 0xc6, 0x77, 0x0c, 0x7c, 0x1e, 0x30, 0xa7, 0x8a, 0x4e, 0xd0, 0xd0, 0x21, 0x0f,
	0x18, 0xb9, 0x0e, 0x8d, 0x98, 0x9f, 0x85, 0x11, 0x73, 0x6a, 0x7a, 0xa0, 0xb6, 0xc8, 0x2d, 0xe8,
	0x09, 0xe6, 0x67, 0x4c, 0x0e, 0x7c, 0x9e, 0x48, 0x96, 0x48, 0xa7, 0x8e, 0xfe, 0xae, 0x46, 0x0f,
	0x35, 0x48, 0x36, 0xa0, 0x25, 0x24, 0xcf, 0xd8, 0x20, 0x0c, 0x9c, 0xc6, 0xb6, 0xb5, 0x5b, 0xf3,
	0x9a, 0x68, 0x1f, 0x05, 0xe4, 0x26, 0x40, 0x4a, 0x33, 0x99, 0xb0, 0x4c, 0x39, 0x9b, 0xe8, 0xb4,
	0x0d, 0x72, 0x14, 0xe0, 0x48, 0x9f, 0xa7, 0x38, 0xb2, 0x65, 0x46, 0x2a, 0xfb, 0x28, 0x50, 0xd9,
	0xe4, 0x42, 0x0f, 0xb3, 0xd1, 0xd3, 0x50, 0xe6, 0x51, 0xa0, 0x16, 0xcb, 0x5e, 0x48, 0x96, 0x04,
	0x0e, 0xe8, 0xc5, 0x6a, 0x8b, 0xbc, 0x09, 0x5d, 0x9e, 0x05, 0x98, 0xa4, 0x5e, 0x6b, 0x7b, 0xdb,
	0xda, 0x6d, 0x1f, 0xac, 0xdd, 0x37, 0x04, 0xbe, 0xa7, 0x9c, 0x66, 0xc9, 0x5e, 0x87, 0x97, 0x2c,
	0xf7, 0xb3, 0x3a, 0xac, 0x96, 0x0a, 0x6d, 0x28, 0x59, 0x5c, 0xe9, 0x3b, 0xd0, 0xa7, 0xbe, 0xcf,
	0xf3, 0x44, 0x0e, 0xce, 0x68, 0x44, 0x13, 0x9f, 0x61, 0xc5, 0x2d, 0xaf, 0x67, 0xe0, 0xb7, 0x35,
	0x4a, 0x76, 0xa0, 0xe3, 0x67, 0x2c, 0x08, 0xe5, 0x40, 0x72, 0x49, 0x23, 0x2c, 0x7d, 0xdd, 0x6b,
	0x6b, 0xec, 0x54, 0x41, 0xaa, 0xc6, 0x26, 0xa4, 0x78, 0x55, 0x0d, 0x83, 0xba, 0x1a, 0x2d, 0xde,
	0x54, 0x22, 0xb7, 0x3e, 0x41, 0xee, 0x0d, 0xb0, 0x0d, 0xb9, 0xa6, 0xfa, 0xb6, 0xd7, 0xd2, 0xc0,
	0x51, 0x30, 0xcd, 0x7c, 0x73, 0x86, 0x79, 0x02, 0xb5, 0x84, 0xc6, 0x0c, 0x8b, 0x6f, 0x7b, 0xf8,
	0xac, 0x0a, 0x3c, 0x64, 0x49, 0xc0, 0x32, 0x2c, 0xbc, 0xed, 0x19, 0x8b, 0xac, 0x41, 0x9d, 0xc5,
	0x34, 0x8c, 0x4c, 0xdd, 0xb5, 0x51, 0xd2, 0x4e, 0x7b, 0x42, 0x3b, 0xd7, 0xa1, 0x21, 0x24, 0x95,
	0xb9, 0x70, 0x3a, 0x98, 0x8f, 0xb1, 0x14, 0xe5, 0xc3, 0x8c, 0x06, 0x48, 0x79, 0x57, 0x97, 0x15,
	0x6d, 0x2d, 0x16, 0xed, 0xc2, 0x25, 0xf5, 0xd0, 0x69, 0x23, 0x72, 0xa2, 0xd6, 0xa5, 0xdd, 0x89,
	0x1c, 0x04, 0x54, 0x32, 0xa7, 0x3f, 0x72, 0x27, 0xf2, 0x31, 0x95, 0x4c, 0xe5, 0x1a, 0x8a, 0x01,
	0x8b, 0xd3, 0x88, 0x5f, 0x30, 0xe6, 0xac, 0x6c, 0x5b, 0xbb, 0x2d, 0x0f, 0x42, 0xf1, 0x8e, 0x41,
	0xd4, 0x8a, 0xe8, 0x39, 0x95, 0x34, 0x73, 0x56, 0xf5, 0x4a, 0xb5, 0xa5, 0x78, 0x4e, 0xe9, 0x05,
	0x16, 0x88, 0xe8, 0x05, 0x19, 0x53, 0xd1, 0x97, 0x66, 0x3c, 0xe6, 0xaa, 0xb7, 0xd5, 0x7a, 0xaf,
	0xa1, 0xbb, 0x3d, 0xc2, 0x8e, 0x02, 0xb2, 0x0b, 0x4d, 0xad, 0x2f, 0xe1, 0xac, 0x6d, 0x57, 0x77,
	0xdb, 0x07, 0xbd, 0x42, 0x6f, 0x87, 0xf8, 0xe3, 0x15, 0x6e, 0xb2, 0x05, 0xf6, 0x30, 0x63, 0x4c,
	0x86, 0xc9, 0x50, 0x38, 0xeb, 0xc5, 0xea, 0x0d, 0xe0, 0xfe, 0x5c, 0x85, 0x86, 0x1e, 0x81, 0x54,
	0x73, 0x55, 0x05, 0x6e, 0x74, 0xd7, 0x50, 0xe6, 0x09, 0x27, 0x3d, 0xa8, 0x84, 0x81, 0xe9, 0xed,
	0x4a, 0x18, 0x8c, 0xc8, 0xab, 0x96, 0xc8, 0x23, 0x50, 0xc3, 0x4c, 0x74, 0x23, 0xe3, 0xb3, 0x4a,
	0x3c, 0xcd, 0x58, 0x4a, 0x2f, 0x50, 0x3a, 0x96, 0x67, 0x2c, 0x25, 0x1d, 0x79, 0x91, 0x32, 0xad,
	0x0d, 0x23, 0x1d, 0x05, 0xa0, 0x32, 0x6e, 0x80, 0xea, 0xd3, 0xc1, 0x39, 0x8d, 0x72, 0x2d, 0x1c,
	0xcb, 0x6b, 0xa5, 0x34, 0x7b, 0xaa, 0x6c, 0x35, 0x8b, 0x0a, 0x2c, 0x64, 0xa3, 0x9e, 0x15, 0x3d,
	0x42, 0xd2, 0xcc, 0xd0, 0xa3, 0xa5, 0x63, 0x23, 0x82, 0xf4, 0xec, 0x40, 0x87, 0xbd, 0x48, 0xc3,
	0x8c, 0x05, 0x3a, 0x40, 0x8b, 0xa8, 0x6d, 0x30, 0x0c, 0x19, 0x4b, 0xa6, 0x3d, 0x21, 0x19, 0xd5,
	0x6e, 0xe7, 0x34, 0x8c, 0xe8, 0x59, 0xa4, 0x16, 0x9b, 0x27, 0xd2, 0x68, 0xaa, 0x37, 0x82, 0x0f,
	0x15, 0xaa, 0xb4, 0x95, 0x0b, 0x36, 0xc0, 0xa5, 0x19, 0x6d, 0xe5, 0x82, 0x9d, 0xaa, 0xd5, 0x4d,
	0x53, 0xd9, 0x9b, 0xa5, 0xf2, 0x0e, 0xf4, 0x75, 0x02, 0x32, 0x8c, 0x99, 0x90, 0x34, 0x4e, 0x8d,
	0xc8, 0x7a, 0x08, 0x9f, 0x16, 0x28, 0xd9, 0x83, 0xd5, 0x22, 0x95, 0x71, 0xe8, 0x0a, 0x86, 0xae,
	0x18, 0xc7, 0x28, 0xd8, 0xfd, 0x00, 0x6c, 0xa3, 0x04, 0xf6, 0x7c, 0x31, 0xb5, 0xff, 0x87, 0x6e,
	0x4a, 0x85, 0xf8, 0x84, 0x67, 0x81, 0xa6, 0x43, 0xb3, 0xdc, 0x29, 0x40, 0xa4, 0x64, 0x05, 0xaa,
	0xcf, 0xe5, 0x85, 0xd9, 0x44, 0xd4, 0xa3, 0xfb, 0x6d, 0x05, 0x3a, 0xe5, 0x7d, 0x8d, 0xdc, 0x86,
	0xbe, 0xde, 0x04, 0x65, 0xe8, 0x7f, 0xcc, 0xa4, 0xca, 0x54, 0x4f, 0xa4, 0xf7, 0xc6, 0x53, 0x44,
	0x8f, 0x02, 0xb2, 0x0e, 0x8d, 0x94, 0x8b, 0xc1, 0x48, 0x4e, 0xf5, 0x94, 0x0b, 0xbd, 0x1f, 0x2b,
	0xb8, 0x74, 0x4c, 0x34, 0x53, 0x2e, 0x70, 0xf2, 0x0d, 0x68, 0x49, 0x24, 0x20, 0xe1, 0x46, 0x5c,
	0x4d, 0xb4, 0x4f, 0x38, 0x32, 0x4f, 0x23, 0x26, 0xb0, 0x1a, 0x66, 0x7b, 0xb2, 0x11, 0x51, 0x65,
	0x18, 0xbb, 0x91, 0xf7, 0x46, 0xc9, 0x5d, 0x08, 0x63, 0x98, 0x71, 0x21, 0x06, 0x34, 0x46, 0x6a,
	0xb5, 0xd6, 0xda, 0x88, 0x3d, 0x42, 0x48, 0xbd, 0x21, 0x61, 0xb2, 0x08, 0x68, 0x61, 0x80, 0x9d,
	0x30, 0x69, 0xdc, 0x7b, 0xd0, 0x4a, 0x33, 0x1e, 0xe4, 0xbe, 0x14, 0x8e, 0x8d, 0x4d, 0xd8, 0x2f,
	0x9a, 0xf0, 0x89, 0xc6, 0xbd, 0x51, 0x80, 0xfb, 0x95, 0x05, 0xdd, 0x63, 0xb3, 0x01, 0xea, 0x9a,
	0x95, 0xb6, 0x56, 0x6b, 0xd9, 0xb9, 0x59, 0x59, 0x72, 0x6e, 0x56, 0x2f, 0x39, 0x37, 0x6b, 0x73,
	0xce, 0x4d, 0xf7, 0x7b, 0x0b, 0x9a, 0x66, 0x81, 0xa6, 0xb7, 0xad, 0x99, 0xde, 0xae, 0xcc, 0xe9,
	0xed, 0x6a, 0xa9, 0xb7, 0x8d, 0x26, 0x6a, 0x58, 0x13, 0xf5, 0xa8, 0xb6, 0xe9, 0x34, 0x0b, 0x7d,
	0x66, 0x9a, 0x5d, 0x1b, 0xe4, 0x01, 0xb4, 0xa9, 0xef, 0x33, 0x21, 0x78, 0x16, 0x32, 0xe1, 0x34,
	0xe6, 0x97, 0xa9, 0x1c, 0x43, 0x1e, 0x00, 0x50, 0x29, 0xb3, 0xf0, 0x2c, 0x97, 0x4c, 0x38, 0x4d,
	0x1c, 0xb1, 0x5a, 0x8c, 0x78, 0x54, 0x78, 0xbc, 0x52, 0x90, 0xfb, 0xa5, 0x05, 0xf6, 0xc8, 0x33,
	0xca, 0xc1, 0x2a, 0xe5, 0x70, 0x03, 0x6c, 0xf5, 0x5b, 0xae, 0x68, 0x4b, 0x01, 0x58, 0xcf, 0x35,
	0xa8, 0xeb, 0xfd, 0x46, 0x67, 0xa8, 0x0d, 0xc5, 0x3e, 0x3e, 0x0c, 0x4a, 0x1b, 0x9b, 0x8d, 0x48,
	0x31, 0x68, 0x36, 0x5f, 0xf7, 0xbb, 0x0a, 0x6c, 0x1c, 0xd2, 0xc8, 0xcf, 0x23, 0x2a, 0xd9, 0x93,
	0xa2, 0xcb, 0x2f, 0xbf, 0x44, 0x95, 0xef, 0x32, 0x95, 0x65, 0x77, 0x99, 0xea, 0xb2, 0xbb, 0x4c,
	0x6d, 0xe1, 0x5d, 0xa6, 0x3e, 0x71, 0x97, 0x99, 0xb9, 0xb3, 0x34, 0xae, 0x7a, 0x67, 0x21, 0x6f,
	0x41, 0x6f, 0x24, 0x4e, 0x3d, 0xb6, 0x89, 0x63, 0xd7, 0x8b, 0xb1, 0x13, 0x22, 0xf7, 0xba, 0xf1,
	0x84, 0xe6, 0xc7, 0x97, 0xa8, 0x56, 0xf9, 0x12, 0xe5, 0x7e, 0x61, 0xc1, 0xe6, 0xbc, 0xb2, 0x5d,
	0x7a, 0x25, 0x9a, 0xde, 0x5f, 0x2b, 0x4b, 0x8f, 0xca, 0xea, 0xd2, 0xa3, 0x52, 0x91, 0xb7, 0xf6,
	0x94, 0x65, 0xe1, 0x87, 0x17, 0xda, 0x23, 0x2e, 0xe7, 0x6d, 0xb6, 0x1c, 0x95, 0xbf, 0x51, 0x8e,
	0x32, 0xeb, 0xd5, 0x65, 0xac, 0xd7, 0x96, 0xb1, 0x5e, 0x5f, 0xc8, 0x7a, 0x63, 0x82, 0xf5, 0xbd,
	0x71, 0x21, 0xa6, 0xba, 0x6a, 0x74, 0x52, 0x8c, 0xaf, 0x0d, 0x77, 0x61, 0x25, 0x4c, 0xfc, 0x28,
	0x0f, 0xd8, 0x20, 0x66, 0x92, 0xe2, 0x1f, 0x89, 0x16, 0xde, 0x6d, 0xfa, 0x06, 0x3f, 0x36, 0xb0,
	0xfb, 0xa7, 0x05, 0xeb, 0x53, 0x65, 0xbb, 0x94, 0x37, 0x07, 0x9a, 0x22, 0xc7, 0xa6, 0xc7, 0x82,
	0xb5, 0xbc, 0xc2, 0x54, 0x89, 0xb3, 0x2c, 0xe3, 0x13, 0x7f, 0x1a, 0x6c, 0x44, 0xb0, 0xed, 0x1c,
	0x68, 0xc6, 0x4c, 0x08, 0x3a, 0x2c, 0x5a, 0xb2, 0x30, 0xd5, 0x59, 0x96, 0x99, 0x89, 0xf5, 0x58,
	0x7d, 0x22, 0x74, 0x0a, 0x10, 0x87, 0xdf, 0x85, 0x95, 0x52, 0xd0, 0x58, 0xfc, 0xb6, 0xd7, 0x1f,
	0xc7, 0x69, 0x72, 0x76, 0xa1, 0x19, 0x30, 0x49, 0xc3, 0xa8, 0x28, 0xd7, 0x8c, 0x6e, 0x8c, 0xdb,
	0xfd, 0xa3, 0x02, 0xeb, 0x87, 0x3c, 0x11, 0xb9, 0xda, 0x4f, 0xae, 0x28, 0x9c, 0xdb, 0xd0, 0x3f,
	0xa3, 0xd2, 0x7f, 0x56, 0x3a, 0x31, 0xb5, 0x76, 0xbb, 0x08, 0x8f, 0x4e, 0xcc, 0x97, 0x2b, 0x91,
	0x7f, 0xd6, 0xdd, 0x33, 0xdb, 0x4a, 0xeb, 0xca, 0xdb, 0x4a, 0x49, 0x9b, 0xf6, 0x65, 0xda, 0x74,
	0x7f, 0xb2, 0xe0, 0xfa, 0x74, 0xbd, 0x5f, 0x01, 0xc5, 0xb9, 0xbf, 0x57, 0x60, 0xed, 0x50, 0xfd,
	0xed, 0x8a, 0xfe, 0x95, 0xd1, 0x4b, 0x90, 0xd1, 0x8f, 0x16, 0xac, 0x4f, 0x95, 0xfb, 0x15, 0x50,
	0xd1, 0xc1, 0x6f, 0x75, 0xe8, 0xea, 0x84, 0xde, 0x67, 0xd9, 0xb9, 0xba, 0x84, 0x85, 0x00, 0x8f,
	0x59, 0xcc, 0x8f, 0x99, 0x7c, 0xc6, 0x03, 0x72, 0xad, 0x28, 0x49, 0xe9, 0x5b, 0xd1, 0xe6, 0xda,
	0x24, 0xa8, 0xdf, 0xe8, 0xbe, 0xfe, 0xf9, 0x0f, 0xbf, 0x7c, 0x53, 0xb9, 0xe7, 0xde, 0xc2, 0x0f,
	0x4e, 0xe7, 0x07, 0xfb, 0x29, 0x17, 0xc5, 0xf7, 0x29, 0xf6, 0x82, 0xc6, 0x69, 0xc4, 0xf6, 0xc7,
	0x6f, 0x7e, 0x68, 0xdd, 0x23, 0x21, 0xd8, 0xa3, 0x2f, 0x1a, 0xc4, 0x29, 0x5e, 0x3a, 0xfd, 0x35,
	0x69, 0x73, 0x63, 0x8e, 0xc7, 0xcc, 0x79, 0x07, 0xe7, 0xdc, 0x71, 0xb7, 0xe6, 0xcc, 0x39, 0x2c,
	0xa2, 0xd5, 0x54, 0x5f, 0x5b, 0x40, 0x66, 0xef, 0x0c, 0x64, 0x67, 0xc4, 0xf8, 0xa2, 0x6b, 0xd8,
	0xa6, 0xbb, 0x2c, 0xe4, 0x0a, 0xa9, 0xfb, 0x33, 0xc3, 0xd4, 0x7a, 0x2e, 0xa0, 0x3b, 0x71, 0x0a,
	0x92, 0xad, 0x62, 0x9a, 0x79, 0x77, 0x8a, 0xcd, 0x9b, 0x0b, 0xbc, 0x66, 0xfe, 0x3d, 0x9c, 0xff,
	0x96, 0xbb, 0x3d, 0x67, 0xfe, 0xf3, 0xf2, 0x08, 0x35, 0xf5, 0xa7, 0xd0, 0x9b, 0xdc, 0x0f, 0xc9,
	0xcd, 0xb1, 0xee, 0xe7, 0x9c, 0x4b, 0x9b, 0xff, 0x5d, 0xe4, 0x36, 0xb3, 0xbf, 0x86, 0xb3, 0xdf,
	0x76, 0x77, 0xe6, 0x65, 0x3f, 0x31, 0xc4, 0x64, 0x3e, 0xd1, 0x47, 0xe3, 0xcc, 0xe7, 0xed, 0x66,
	0xe3, 0xcc, 0xe7, 0x36, 0xdf, 0xd2, 0xcc, 0xfd, 0xf2, 0x88, 0x87, 0xd6, 0xbd, 0xb3, 0x06, 0x7e,
	0xf9, 0x7c, 0xe3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xe2, 0x41, 0x7e, 0x3f, 0x15, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CouponServiceClient interface {
	// 示例方法
	DemoMethod(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
	// 根据卡号/会员号/手机号码获取会员信息，以及相关的会员促销和会员卡券信息
	GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error)
	// 用于计算第三方的促销
	CalculatePromotion(ctx context.Context, in *CalculatePromotionRequest, opts ...grpc.CallOption) (*CalculatePromotionResponse, error)
	// 用于验证卡券是否可以使用，包括会员卡券和非会员卡券
	VerifyCoupons(ctx context.Context, in *VerifyCouponsRequest, opts ...grpc.CallOption) (*VerifyCouponsResponse, error)
	// 用于核销卡券
	ConsumeCoupons(ctx context.Context, in *ConsumeCouponsRequest, opts ...grpc.CallOption) (*ConsumeCouponsResponse, error)
	// 用于反核销卡券
	CancelCoupons(ctx context.Context, in *CancelCouponsRequest, opts ...grpc.CallOption) (*CancelCouponsResponse, error)
}

type couponServiceClient struct {
	cc *grpc.ClientConn
}

func NewCouponServiceClient(cc *grpc.ClientConn) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) DemoMethod(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/DemoMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetMember(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error) {
	out := new(GetMemberResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/GetMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) CalculatePromotion(ctx context.Context, in *CalculatePromotionRequest, opts ...grpc.CallOption) (*CalculatePromotionResponse, error) {
	out := new(CalculatePromotionResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/CalculatePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) VerifyCoupons(ctx context.Context, in *VerifyCouponsRequest, opts ...grpc.CallOption) (*VerifyCouponsResponse, error) {
	out := new(VerifyCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/VerifyCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ConsumeCoupons(ctx context.Context, in *ConsumeCouponsRequest, opts ...grpc.CallOption) (*ConsumeCouponsResponse, error) {
	out := new(ConsumeCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/ConsumeCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) CancelCoupons(ctx context.Context, in *CancelCouponsRequest, opts ...grpc.CallOption) (*CancelCouponsResponse, error) {
	out := new(CancelCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/CancelCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
type CouponServiceServer interface {
	// 示例方法
	DemoMethod(context.Context, *DemoRequest) (*DemoResponse, error)
	// 根据卡号/会员号/手机号码获取会员信息，以及相关的会员促销和会员卡券信息
	GetMember(context.Context, *GetMemberRequest) (*GetMemberResponse, error)
	// 用于计算第三方的促销
	CalculatePromotion(context.Context, *CalculatePromotionRequest) (*CalculatePromotionResponse, error)
	// 用于验证卡券是否可以使用，包括会员卡券和非会员卡券
	VerifyCoupons(context.Context, *VerifyCouponsRequest) (*VerifyCouponsResponse, error)
	// 用于核销卡券
	ConsumeCoupons(context.Context, *ConsumeCouponsRequest) (*ConsumeCouponsResponse, error)
	// 用于反核销卡券
	CancelCoupons(context.Context, *CancelCouponsRequest) (*CancelCouponsResponse, error)
}

// UnimplementedCouponServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCouponServiceServer struct {
}

func (*UnimplementedCouponServiceServer) DemoMethod(ctx context.Context, req *DemoRequest) (*DemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoMethod not implemented")
}
func (*UnimplementedCouponServiceServer) GetMember(ctx context.Context, req *GetMemberRequest) (*GetMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (*UnimplementedCouponServiceServer) CalculatePromotion(ctx context.Context, req *CalculatePromotionRequest) (*CalculatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePromotion not implemented")
}
func (*UnimplementedCouponServiceServer) VerifyCoupons(ctx context.Context, req *VerifyCouponsRequest) (*VerifyCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCoupons not implemented")
}
func (*UnimplementedCouponServiceServer) ConsumeCoupons(ctx context.Context, req *ConsumeCouponsRequest) (*ConsumeCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeCoupons not implemented")
}
func (*UnimplementedCouponServiceServer) CancelCoupons(ctx context.Context, req *CancelCouponsRequest) (*CancelCouponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCoupons not implemented")
}

func RegisterCouponServiceServer(s *grpc.Server, srv CouponServiceServer) {
	s.RegisterService(&_CouponService_serviceDesc, srv)
}

func _CouponService_DemoMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DemoMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/DemoMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DemoMethod(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/GetMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetMember(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_CalculatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CalculatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/CalculatePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CalculatePromotion(ctx, req.(*CalculatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_VerifyCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).VerifyCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/VerifyCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).VerifyCoupons(ctx, req.(*VerifyCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ConsumeCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ConsumeCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/ConsumeCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ConsumeCoupons(ctx, req.(*ConsumeCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_CancelCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CancelCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/CancelCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CancelCoupons(ctx, req.(*CancelCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CouponService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DemoMethod",
			Handler:    _CouponService_DemoMethod_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _CouponService_GetMember_Handler,
		},
		{
			MethodName: "CalculatePromotion",
			Handler:    _CouponService_CalculatePromotion_Handler,
		},
		{
			MethodName: "VerifyCoupons",
			Handler:    _CouponService_VerifyCoupons_Handler,
		},
		{
			MethodName: "ConsumeCoupons",
			Handler:    _CouponService_ConsumeCoupons_Handler,
		},
		{
			MethodName: "CancelCoupons",
			Handler:    _CouponService_CancelCoupons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ui/proto/coupon/coupon.proto",
}
